<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BlurHashSharp"/>
        <PackageReference Include="DotNetEnv"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Minio"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
        <PackageReference Include="Scalar.AspNetCore"/>
        <PackageReference Include="SixLabors.ImageSharp"/>
        <PackageReference Include="SkiaSharp"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ResonanceSystem.Core\Shiron.ResonanceSystem.Core.csproj"/>
        <ProjectReference Include="..\ResonanceSystem.DB\Shiron.ResonanceSystem.DB.csproj"/>
        <ProjectReference Include="..\ResonanceSystem.Services\Shiron.ResonanceSystem.Services.csproj"/>
    </ItemGroup>
</Project>