/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.HonamiSystem.Server | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { BodyType, ErrorType } from "../../lib/custom-instance";

import { customInstance } from "../../lib/custom-instance";
import type {
	AgentChatEntry,
	AgentResponse,
	CreateAgentRequest,
	SetAgentPersonaRequest,
	UpdateAgentRequest,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Create a new AI agent
 */
export const createAgent = (
	createAgentRequest: BodyType<CreateAgentRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgentResponse>(
		{
			url: `/api/agents`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createAgentRequest,
			signal,
		},
		options,
	);
};

export const getCreateAgentMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createAgent>>,
		TError,
		{ data: BodyType<CreateAgentRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createAgent>>,
	TError,
	{ data: BodyType<CreateAgentRequest> },
	TContext
> => {
	const mutationKey = ["createAgent"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createAgent>>,
		{ data: BodyType<CreateAgentRequest> }
	> = (props) => {
		const { data } = props ?? {};

		return createAgent(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateAgentMutationResult = NonNullable<
	Awaited<ReturnType<typeof createAgent>>
>;
export type CreateAgentMutationBody = BodyType<CreateAgentRequest>;
export type CreateAgentMutationError = ErrorType<void>;

export const useCreateAgent = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createAgent>>,
			TError,
			{ data: BodyType<CreateAgentRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createAgent>>,
	TError,
	{ data: BodyType<CreateAgentRequest> },
	TContext
> => {
	return useMutation(getCreateAgentMutationOptions(options), queryClient);
};
/**
 * List the current user's agents
 */
export const listAgents = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgentResponse[]>(
		{ url: `/api/agents`, method: "GET", signal },
		options,
	);
};

export const getListAgentsQueryKey = () => {
	return [`/api/agents`] as const;
};

export const getListAgentsQueryOptions = <
	TData = Awaited<ReturnType<typeof listAgents>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>
	>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListAgentsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listAgents>>> = ({
		signal,
	}) => listAgents(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listAgents>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAgentsQueryResult = NonNullable<
	Awaited<ReturnType<typeof listAgents>>
>;
export type ListAgentsQueryError = ErrorType<void>;

export function useListAgents<
	TData = Awaited<ReturnType<typeof listAgents>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAgents>>,
					TError,
					Awaited<ReturnType<typeof listAgents>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAgents<
	TData = Awaited<ReturnType<typeof listAgents>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAgents>>,
					TError,
					Awaited<ReturnType<typeof listAgents>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAgents<
	TData = Awaited<ReturnType<typeof listAgents>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListAgents<
	TData = Awaited<ReturnType<typeof listAgents>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListAgentsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get an agent by ID
 */
export const getAgent = (
	agentId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgentResponse>(
		{ url: `/api/agents/${agentId}`, method: "GET", signal },
		options,
	);
};

export const getGetAgentQueryKey = (agentId: string) => {
	return [`/api/agents/${agentId}`] as const;
};

export const getGetAgentQueryOptions = <
	TData = Awaited<ReturnType<typeof getAgent>>,
	TError = ErrorType<void>,
>(
	agentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetAgentQueryKey(agentId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgent>>> = ({
		signal,
	}) => getAgent(agentId, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!agentId,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetAgentQueryResult = NonNullable<
	Awaited<ReturnType<typeof getAgent>>
>;
export type GetAgentQueryError = ErrorType<void>;

export function useGetAgent<
	TData = Awaited<ReturnType<typeof getAgent>>,
	TError = ErrorType<void>,
>(
	agentId: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAgent>>,
					TError,
					Awaited<ReturnType<typeof getAgent>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAgent<
	TData = Awaited<ReturnType<typeof getAgent>>,
	TError = ErrorType<void>,
>(
	agentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAgent>>,
					TError,
					Awaited<ReturnType<typeof getAgent>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAgent<
	TData = Awaited<ReturnType<typeof getAgent>>,
	TError = ErrorType<void>,
>(
	agentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAgent<
	TData = Awaited<ReturnType<typeof getAgent>>,
	TError = ErrorType<void>,
>(
	agentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetAgentQueryOptions(agentId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Update agent metadata
 */
export const updateAgent = (
	agentId: string,
	updateAgentRequest: BodyType<UpdateAgentRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgentResponse>(
		{
			url: `/api/agents/${agentId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateAgentRequest,
			signal,
		},
		options,
	);
};

export const getUpdateAgentMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateAgent>>,
		TError,
		{ agentId: string; data: BodyType<UpdateAgentRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateAgent>>,
	TError,
	{ agentId: string; data: BodyType<UpdateAgentRequest> },
	TContext
> => {
	const mutationKey = ["updateAgent"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateAgent>>,
		{ agentId: string; data: BodyType<UpdateAgentRequest> }
	> = (props) => {
		const { agentId, data } = props ?? {};

		return updateAgent(agentId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateAgentMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateAgent>>
>;
export type UpdateAgentMutationBody = BodyType<UpdateAgentRequest>;
export type UpdateAgentMutationError = ErrorType<void>;

export const useUpdateAgent = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateAgent>>,
			TError,
			{ agentId: string; data: BodyType<UpdateAgentRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateAgent>>,
	TError,
	{ agentId: string; data: BodyType<UpdateAgentRequest> },
	TContext
> => {
	return useMutation(getUpdateAgentMutationOptions(options), queryClient);
};
/**
 * Delete an agent
 */
export const deleteAgent = (
	agentId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/agents/${agentId}`, method: "DELETE", signal },
		options,
	);
};

export const getDeleteAgentMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteAgent>>,
		TError,
		{ agentId: string },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteAgent>>,
	TError,
	{ agentId: string },
	TContext
> => {
	const mutationKey = ["deleteAgent"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteAgent>>,
		{ agentId: string }
	> = (props) => {
		const { agentId } = props ?? {};

		return deleteAgent(agentId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteAgentMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteAgent>>
>;

export type DeleteAgentMutationError = ErrorType<void>;

export const useDeleteAgent = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteAgent>>,
			TError,
			{ agentId: string },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteAgent>>,
	TError,
	{ agentId: string },
	TContext
> => {
	return useMutation(getDeleteAgentMutationOptions(options), queryClient);
};
/**
 * Assign or unassign a persona to an agent
 */
export const setAgentPersona = (
	agentId: string,
	setAgentPersonaRequest: BodyType<SetAgentPersonaRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgentResponse>(
		{
			url: `/api/agents/${agentId}/persona`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: setAgentPersonaRequest,
			signal,
		},
		options,
	);
};

export const getSetAgentPersonaMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof setAgentPersona>>,
		TError,
		{ agentId: string; data: BodyType<SetAgentPersonaRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof setAgentPersona>>,
	TError,
	{ agentId: string; data: BodyType<SetAgentPersonaRequest> },
	TContext
> => {
	const mutationKey = ["setAgentPersona"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof setAgentPersona>>,
		{ agentId: string; data: BodyType<SetAgentPersonaRequest> }
	> = (props) => {
		const { agentId, data } = props ?? {};

		return setAgentPersona(agentId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type SetAgentPersonaMutationResult = NonNullable<
	Awaited<ReturnType<typeof setAgentPersona>>
>;
export type SetAgentPersonaMutationBody = BodyType<SetAgentPersonaRequest>;
export type SetAgentPersonaMutationError = ErrorType<void>;

export const useSetAgentPersona = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof setAgentPersona>>,
			TError,
			{ agentId: string; data: BodyType<SetAgentPersonaRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof setAgentPersona>>,
	TError,
	{ agentId: string; data: BodyType<SetAgentPersonaRequest> },
	TContext
> => {
	return useMutation(getSetAgentPersonaMutationOptions(options), queryClient);
};
/**
 * List all chats an agent is assigned to
 */
export const listAgentChats = (
	agentId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgentChatEntry[]>(
		{ url: `/api/agents/${agentId}/chats`, method: "GET", signal },
		options,
	);
};

export const getListAgentChatsQueryKey = (agentId: string) => {
	return [`/api/agents/${agentId}/chats`] as const;
};

export const getListAgentChatsQueryOptions = <
	TData = Awaited<ReturnType<typeof listAgentChats>>,
	TError = ErrorType<void>,
>(
	agentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAgentChats>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListAgentChatsQueryKey(agentId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listAgentChats>>> = ({
		signal,
	}) => listAgentChats(agentId, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!agentId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof listAgentChats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAgentChatsQueryResult = NonNullable<
	Awaited<ReturnType<typeof listAgentChats>>
>;
export type ListAgentChatsQueryError = ErrorType<void>;

export function useListAgentChats<
	TData = Awaited<ReturnType<typeof listAgentChats>>,
	TError = ErrorType<void>,
>(
	agentId: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAgentChats>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAgentChats>>,
					TError,
					Awaited<ReturnType<typeof listAgentChats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAgentChats<
	TData = Awaited<ReturnType<typeof listAgentChats>>,
	TError = ErrorType<void>,
>(
	agentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAgentChats>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAgentChats>>,
					TError,
					Awaited<ReturnType<typeof listAgentChats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAgentChats<
	TData = Awaited<ReturnType<typeof listAgentChats>>,
	TError = ErrorType<void>,
>(
	agentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAgentChats>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListAgentChats<
	TData = Awaited<ReturnType<typeof listAgentChats>>,
	TError = ErrorType<void>,
>(
	agentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAgentChats>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListAgentChatsQueryOptions(agentId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
