/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.ResonanceSystem.API | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	ChangePasswordDto,
	HttpValidationProblemDetails,
	LoginDto,
	RegisterDto,
	UserInfoDto,
} from "../model";

/**
 * Register a new user account
 */
export type registerResponse200 = {
	data: void;
	status: 200;
};

export type registerResponse400 = {
	data: HttpValidationProblemDetails;
	status: 400;
};

export type registerResponseSuccess = registerResponse200 & {
	headers: Headers;
};
export type registerResponseError = registerResponse400 & {
	headers: Headers;
};

export type registerResponse = registerResponseSuccess | registerResponseError;

export const getRegisterUrl = () => {
	return `/api/account/register`;
};

export const register = async (
	registerDto: RegisterDto,
	options?: RequestInit,
): Promise<registerResponse> => {
	const res = await fetch(getRegisterUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(registerDto),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: registerResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as registerResponse;
};

export const getRegisterMutationOptions = <
	TError = HttpValidationProblemDetails,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof register>>,
		TError,
		{ data: RegisterDto },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof register>>,
	TError,
	{ data: RegisterDto },
	TContext
> => {
	const mutationKey = ["register"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof register>>,
		{ data: RegisterDto }
	> = (props) => {
		const { data } = props ?? {};

		return register(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
	Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = RegisterDto;
export type RegisterMutationError = HttpValidationProblemDetails;

export const useRegister = <
	TError = HttpValidationProblemDetails,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof register>>,
			TError,
			{ data: RegisterDto },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof register>>,
	TError,
	{ data: RegisterDto },
	TContext
> => {
	return useMutation(getRegisterMutationOptions(options), queryClient);
};
/**
 * Log in with credentials
 */
export type loginResponse200 = {
	data: void;
	status: 200;
};

export type loginResponse401 = {
	data: void;
	status: 401;
};

export type loginResponseSuccess = loginResponse200 & {
	headers: Headers;
};
export type loginResponseError = loginResponse401 & {
	headers: Headers;
};

export type loginResponse = loginResponseSuccess | loginResponseError;

export const getLoginUrl = () => {
	return `/api/account/login`;
};

export const login = async (
	loginDto: LoginDto,
	options?: RequestInit,
): Promise<loginResponse> => {
	const res = await fetch(getLoginUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(loginDto),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: loginResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as loginResponse;
};

export const getLoginMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof login>>,
		TError,
		{ data: LoginDto },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof login>>,
	TError,
	{ data: LoginDto },
	TContext
> => {
	const mutationKey = ["login"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof login>>,
		{ data: LoginDto }
	> = (props) => {
		const { data } = props ?? {};

		return login(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = LoginDto;
export type LoginMutationError = void;

export const useLogin = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof login>>,
			TError,
			{ data: LoginDto },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof login>>,
	TError,
	{ data: LoginDto },
	TContext
> => {
	return useMutation(getLoginMutationOptions(options), queryClient);
};
/**
 * Log out the current session
 */
export type logoutResponse200 = {
	data: void;
	status: 200;
};

export type logoutResponseSuccess = logoutResponse200 & {
	headers: Headers;
};

export type logoutResponse = logoutResponseSuccess;

export const getLogoutUrl = () => {
	return `/api/account/logout`;
};

export const logout = async (
	options?: RequestInit,
): Promise<logoutResponse> => {
	const res = await fetch(getLogoutUrl(), {
		...options,
		method: "POST",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: logoutResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as logoutResponse;
};

export const getLogoutMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof logout>>,
		TError,
		void,
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof logout>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["logout"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof logout>>,
		void
	> = () => {
		return logout(fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
	Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = unknown;

export const useLogout = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof logout>>,
			TError,
			void,
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof logout>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getLogoutMutationOptions(options), queryClient);
};
/**
 * Get the current authenticated user info
 */
export type getMeResponse200 = {
	data: UserInfoDto;
	status: 200;
};

export type getMeResponse401 = {
	data: void;
	status: 401;
};

export type getMeResponseSuccess = getMeResponse200 & {
	headers: Headers;
};
export type getMeResponseError = getMeResponse401 & {
	headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
	return `/api/account/me`;
};

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
	const res = await fetch(getGetMeUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getMeResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getMeResponse;
};

export const getGetMeQueryKey = () => {
	return [`/api/account/me`] as const;
};

export const getGetMeQueryOptions = <
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = void,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
		signal,
	}) => getMe({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getMe>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = void;

export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = void,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMe>>,
					TError,
					Awaited<ReturnType<typeof getMe>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = void,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMe>>,
					TError,
					Awaited<ReturnType<typeof getMe>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = void,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = void,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMeQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Change the current user's password
 */
export type changePasswordResponse200 = {
	data: void;
	status: 200;
};

export type changePasswordResponse400 = {
	data: void;
	status: 400;
};

export type changePasswordResponseSuccess = changePasswordResponse200 & {
	headers: Headers;
};
export type changePasswordResponseError = changePasswordResponse400 & {
	headers: Headers;
};

export type changePasswordResponse =
	| changePasswordResponseSuccess
	| changePasswordResponseError;

export const getChangePasswordUrl = () => {
	return `/api/account/change-password`;
};

export const changePassword = async (
	changePasswordDto: ChangePasswordDto,
	options?: RequestInit,
): Promise<changePasswordResponse> => {
	const res = await fetch(getChangePasswordUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(changePasswordDto),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: changePasswordResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as changePasswordResponse;
};

export const getChangePasswordMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof changePassword>>,
		TError,
		{ data: ChangePasswordDto },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof changePassword>>,
	TError,
	{ data: ChangePasswordDto },
	TContext
> => {
	const mutationKey = ["changePassword"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof changePassword>>,
		{ data: ChangePasswordDto }
	> = (props) => {
		const { data } = props ?? {};

		return changePassword(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ChangePasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof changePassword>>
>;
export type ChangePasswordMutationBody = ChangePasswordDto;
export type ChangePasswordMutationError = void;

export const useChangePassword = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof changePassword>>,
			TError,
			{ data: ChangePasswordDto },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof changePassword>>,
	TError,
	{ data: ChangePasswordDto },
	TContext
> => {
	return useMutation(getChangePasswordMutationOptions(options), queryClient);
};
