/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.API | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { BodyType, ErrorType } from "../../lib/custom-instance";

import { customInstance } from "../../lib/custom-instance";
import type {
	AddCharacterRequest,
	AddCharacterResponse,
	ClearCollectionResponse,
	CollectionEntrySpherePerks,
	CollectionExportRequest,
	CollectionExportResponse,
	CollectionStatsDto,
	ErrorResponse,
	GetApiCollectionParams,
	ImageStatusResponse,
	ImportRequest,
	ImportResponse,
	ImportSeriesRequest,
	ImportSeriesResponse,
	PaginatedResponseOfCollectionEntryDto,
	SeriesWithCountDto,
	ToggleFavoriteResponse,
	UpdateCollectionRequest,
	UpdateResponse,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getApiCollection = (
	params?: GetApiCollectionParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<PaginatedResponseOfCollectionEntryDto>(
		{ url: `/api/collection`, method: "GET", params, signal },
		options,
	);
};

export const getGetApiCollectionQueryKey = (
	params?: GetApiCollectionParams,
) => {
	return [`/api/collection`, ...(params ? [params] : [])] as const;
};

export const getGetApiCollectionQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiCollection>>,
	TError = ErrorType<void>,
>(
	params?: GetApiCollectionParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollection>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiCollectionQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiCollection>>
	> = ({ signal }) => getApiCollection(params, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiCollection>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiCollectionQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiCollection>>
>;
export type GetApiCollectionQueryError = ErrorType<void>;

export function useGetApiCollection<
	TData = Awaited<ReturnType<typeof getApiCollection>>,
	TError = ErrorType<void>,
>(
	params: undefined | GetApiCollectionParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollection>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiCollection>>,
					TError,
					Awaited<ReturnType<typeof getApiCollection>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCollection<
	TData = Awaited<ReturnType<typeof getApiCollection>>,
	TError = ErrorType<void>,
>(
	params?: GetApiCollectionParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollection>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiCollection>>,
					TError,
					Awaited<ReturnType<typeof getApiCollection>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCollection<
	TData = Awaited<ReturnType<typeof getApiCollection>>,
	TError = ErrorType<void>,
>(
	params?: GetApiCollectionParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollection>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiCollection<
	TData = Awaited<ReturnType<typeof getApiCollection>>,
	TError = ErrorType<void>,
>(
	params?: GetApiCollectionParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollection>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiCollectionQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getApiCollectionStats = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CollectionStatsDto>(
		{ url: `/api/collection/stats`, method: "GET", signal },
		options,
	);
};

export const getGetApiCollectionStatsQueryKey = () => {
	return [`/api/collection/stats`] as const;
};

export const getGetApiCollectionStatsQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiCollectionStats>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getApiCollectionStats>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiCollectionStatsQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiCollectionStats>>
	> = ({ signal }) => getApiCollectionStats(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiCollectionStats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiCollectionStatsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiCollectionStats>>
>;
export type GetApiCollectionStatsQueryError = ErrorType<void>;

export function useGetApiCollectionStats<
	TData = Awaited<ReturnType<typeof getApiCollectionStats>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionStats>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiCollectionStats>>,
					TError,
					Awaited<ReturnType<typeof getApiCollectionStats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCollectionStats<
	TData = Awaited<ReturnType<typeof getApiCollectionStats>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionStats>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiCollectionStats>>,
					TError,
					Awaited<ReturnType<typeof getApiCollectionStats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCollectionStats<
	TData = Awaited<ReturnType<typeof getApiCollectionStats>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionStats>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiCollectionStats<
	TData = Awaited<ReturnType<typeof getApiCollectionStats>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionStats>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiCollectionStatsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getApiCollectionSeries = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<SeriesWithCountDto[]>(
		{ url: `/api/collection/series`, method: "GET", signal },
		options,
	);
};

export const getGetApiCollectionSeriesQueryKey = () => {
	return [`/api/collection/series`] as const;
};

export const getGetApiCollectionSeriesQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiCollectionSeries>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getApiCollectionSeries>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiCollectionSeriesQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiCollectionSeries>>
	> = ({ signal }) => getApiCollectionSeries(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiCollectionSeries>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiCollectionSeriesQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiCollectionSeries>>
>;
export type GetApiCollectionSeriesQueryError = ErrorType<void>;

export function useGetApiCollectionSeries<
	TData = Awaited<ReturnType<typeof getApiCollectionSeries>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionSeries>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiCollectionSeries>>,
					TError,
					Awaited<ReturnType<typeof getApiCollectionSeries>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCollectionSeries<
	TData = Awaited<ReturnType<typeof getApiCollectionSeries>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionSeries>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiCollectionSeries>>,
					TError,
					Awaited<ReturnType<typeof getApiCollectionSeries>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCollectionSeries<
	TData = Awaited<ReturnType<typeof getApiCollectionSeries>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionSeries>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiCollectionSeries<
	TData = Awaited<ReturnType<typeof getApiCollectionSeries>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionSeries>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiCollectionSeriesQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiCollectionExport = (
	collectionExportRequest: BodyType<CollectionExportRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CollectionExportResponse>(
		{
			url: `/api/collection/export`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: collectionExportRequest,
			signal,
		},
		options,
	);
};

export const getPostApiCollectionExportMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiCollectionExport>>,
		TError,
		{ data: BodyType<CollectionExportRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiCollectionExport>>,
	TError,
	{ data: BodyType<CollectionExportRequest> },
	TContext
> => {
	const mutationKey = ["postApiCollectionExport"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiCollectionExport>>,
		{ data: BodyType<CollectionExportRequest> }
	> = (props) => {
		const { data } = props ?? {};

		return postApiCollectionExport(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiCollectionExportMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiCollectionExport>>
>;
export type PostApiCollectionExportMutationBody =
	BodyType<CollectionExportRequest>;
export type PostApiCollectionExportMutationError = ErrorType<void>;

export const usePostApiCollectionExport = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiCollectionExport>>,
			TError,
			{ data: BodyType<CollectionExportRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiCollectionExport>>,
	TError,
	{ data: BodyType<CollectionExportRequest> },
	TContext
> => {
	return useMutation(
		getPostApiCollectionExportMutationOptions(options),
		queryClient,
	);
};
export const postApiCollectionAdd = (
	addCharacterRequest: BodyType<AddCharacterRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AddCharacterResponse>(
		{
			url: `/api/collection/add`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: addCharacterRequest,
			signal,
		},
		options,
	);
};

export const getPostApiCollectionAddMutationOptions = <
	TError = ErrorType<ErrorResponse | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiCollectionAdd>>,
		TError,
		{ data: BodyType<AddCharacterRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiCollectionAdd>>,
	TError,
	{ data: BodyType<AddCharacterRequest> },
	TContext
> => {
	const mutationKey = ["postApiCollectionAdd"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiCollectionAdd>>,
		{ data: BodyType<AddCharacterRequest> }
	> = (props) => {
		const { data } = props ?? {};

		return postApiCollectionAdd(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiCollectionAddMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiCollectionAdd>>
>;
export type PostApiCollectionAddMutationBody = BodyType<AddCharacterRequest>;
export type PostApiCollectionAddMutationError = ErrorType<ErrorResponse | void>;

export const usePostApiCollectionAdd = <
	TError = ErrorType<ErrorResponse | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiCollectionAdd>>,
			TError,
			{ data: BodyType<AddCharacterRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiCollectionAdd>>,
	TError,
	{ data: BodyType<AddCharacterRequest> },
	TContext
> => {
	return useMutation(
		getPostApiCollectionAddMutationOptions(options),
		queryClient,
	);
};
export const postApiCollectionImport = (
	importRequest: BodyType<ImportRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ImportResponse>(
		{
			url: `/api/collection/import`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: importRequest,
			signal,
		},
		options,
	);
};

export const getPostApiCollectionImportMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiCollectionImport>>,
		TError,
		{ data: BodyType<ImportRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiCollectionImport>>,
	TError,
	{ data: BodyType<ImportRequest> },
	TContext
> => {
	const mutationKey = ["postApiCollectionImport"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiCollectionImport>>,
		{ data: BodyType<ImportRequest> }
	> = (props) => {
		const { data } = props ?? {};

		return postApiCollectionImport(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiCollectionImportMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiCollectionImport>>
>;
export type PostApiCollectionImportMutationBody = BodyType<ImportRequest>;
export type PostApiCollectionImportMutationError = ErrorType<void>;

export const usePostApiCollectionImport = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiCollectionImport>>,
			TError,
			{ data: BodyType<ImportRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiCollectionImport>>,
	TError,
	{ data: BodyType<ImportRequest> },
	TContext
> => {
	return useMutation(
		getPostApiCollectionImportMutationOptions(options),
		queryClient,
	);
};
export const postApiCollectionImportSeries = (
	importSeriesRequest: BodyType<ImportSeriesRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ImportSeriesResponse>(
		{
			url: `/api/collection/import-series`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: importSeriesRequest,
			signal,
		},
		options,
	);
};

export const getPostApiCollectionImportSeriesMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiCollectionImportSeries>>,
		TError,
		{ data: BodyType<ImportSeriesRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiCollectionImportSeries>>,
	TError,
	{ data: BodyType<ImportSeriesRequest> },
	TContext
> => {
	const mutationKey = ["postApiCollectionImportSeries"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiCollectionImportSeries>>,
		{ data: BodyType<ImportSeriesRequest> }
	> = (props) => {
		const { data } = props ?? {};

		return postApiCollectionImportSeries(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiCollectionImportSeriesMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiCollectionImportSeries>>
>;
export type PostApiCollectionImportSeriesMutationBody =
	BodyType<ImportSeriesRequest>;
export type PostApiCollectionImportSeriesMutationError = ErrorType<void>;

export const usePostApiCollectionImportSeries = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiCollectionImportSeries>>,
			TError,
			{ data: BodyType<ImportSeriesRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiCollectionImportSeries>>,
	TError,
	{ data: BodyType<ImportSeriesRequest> },
	TContext
> => {
	return useMutation(
		getPostApiCollectionImportSeriesMutationOptions(options),
		queryClient,
	);
};
export const postApiCollectionProcessImages = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ImageStatusResponse>(
		{ url: `/api/collection/process-images`, method: "POST", signal },
		options,
	);
};

export const getPostApiCollectionProcessImagesMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiCollectionProcessImages>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiCollectionProcessImages>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["postApiCollectionProcessImages"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiCollectionProcessImages>>,
		void
	> = () => {
		return postApiCollectionProcessImages(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiCollectionProcessImagesMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiCollectionProcessImages>>
>;

export type PostApiCollectionProcessImagesMutationError = ErrorType<void>;

export const usePostApiCollectionProcessImages = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiCollectionProcessImages>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiCollectionProcessImages>>,
	TError,
	void,
	TContext
> => {
	return useMutation(
		getPostApiCollectionProcessImagesMutationOptions(options),
		queryClient,
	);
};
export const getImageStatus = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ImageStatusResponse>(
		{ url: `/api/collection/image-status`, method: "GET", signal },
		options,
	);
};

export const getGetImageStatusQueryKey = () => {
	return [`/api/collection/image-status`] as const;
};

export const getGetImageStatusQueryOptions = <
	TData = Awaited<ReturnType<typeof getImageStatus>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getImageStatus>>, TError, TData>
	>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetImageStatusQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getImageStatus>>> = ({
		signal,
	}) => getImageStatus(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getImageStatus>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetImageStatusQueryResult = NonNullable<
	Awaited<ReturnType<typeof getImageStatus>>
>;
export type GetImageStatusQueryError = ErrorType<void>;

export function useGetImageStatus<
	TData = Awaited<ReturnType<typeof getImageStatus>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getImageStatus>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getImageStatus>>,
					TError,
					Awaited<ReturnType<typeof getImageStatus>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetImageStatus<
	TData = Awaited<ReturnType<typeof getImageStatus>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getImageStatus>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getImageStatus>>,
					TError,
					Awaited<ReturnType<typeof getImageStatus>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetImageStatus<
	TData = Awaited<ReturnType<typeof getImageStatus>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getImageStatus>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetImageStatus<
	TData = Awaited<ReturnType<typeof getImageStatus>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getImageStatus>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetImageStatusQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const deleteApiCollectionClear = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ClearCollectionResponse>(
		{ url: `/api/collection/clear`, method: "DELETE", signal },
		options,
	);
};

export const getDeleteApiCollectionClearMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteApiCollectionClear>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteApiCollectionClear>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["deleteApiCollectionClear"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteApiCollectionClear>>,
		void
	> = () => {
		return deleteApiCollectionClear(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteApiCollectionClearMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiCollectionClear>>
>;

export type DeleteApiCollectionClearMutationError = ErrorType<void>;

export const useDeleteApiCollectionClear = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteApiCollectionClear>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteApiCollectionClear>>,
	TError,
	void,
	TContext
> => {
	return useMutation(
		getDeleteApiCollectionClearMutationOptions(options),
		queryClient,
	);
};
export const putApiCollectionId = (
	id: string,
	updateCollectionRequest: BodyType<UpdateCollectionRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UpdateResponse>(
		{
			url: `/api/collection/${id}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateCollectionRequest,
			signal,
		},
		options,
	);
};

export const getPutApiCollectionIdMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putApiCollectionId>>,
		TError,
		{ id: string; data: BodyType<UpdateCollectionRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putApiCollectionId>>,
	TError,
	{ id: string; data: BodyType<UpdateCollectionRequest> },
	TContext
> => {
	const mutationKey = ["putApiCollectionId"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putApiCollectionId>>,
		{ id: string; data: BodyType<UpdateCollectionRequest> }
	> = (props) => {
		const { id, data } = props ?? {};

		return putApiCollectionId(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutApiCollectionIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof putApiCollectionId>>
>;
export type PutApiCollectionIdMutationBody = BodyType<UpdateCollectionRequest>;
export type PutApiCollectionIdMutationError = ErrorType<void>;

export const usePutApiCollectionId = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putApiCollectionId>>,
			TError,
			{ id: string; data: BodyType<UpdateCollectionRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putApiCollectionId>>,
	TError,
	{ id: string; data: BodyType<UpdateCollectionRequest> },
	TContext
> => {
	return useMutation(
		getPutApiCollectionIdMutationOptions(options),
		queryClient,
	);
};
export const deleteApiCollectionId = (
	id: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/collection/${id}`, method: "DELETE", signal },
		options,
	);
};

export const getDeleteApiCollectionIdMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteApiCollectionId>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteApiCollectionId>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["deleteApiCollectionId"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteApiCollectionId>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return deleteApiCollectionId(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteApiCollectionIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiCollectionId>>
>;

export type DeleteApiCollectionIdMutationError = ErrorType<void>;

export const useDeleteApiCollectionId = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteApiCollectionId>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteApiCollectionId>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getDeleteApiCollectionIdMutationOptions(options),
		queryClient,
	);
};
export const postApiCollectionIdToggleFavorite = (
	id: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ToggleFavoriteResponse>(
		{ url: `/api/collection/${id}/toggle-favorite`, method: "POST", signal },
		options,
	);
};

export const getPostApiCollectionIdToggleFavoriteMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiCollectionIdToggleFavorite>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiCollectionIdToggleFavorite>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["postApiCollectionIdToggleFavorite"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiCollectionIdToggleFavorite>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return postApiCollectionIdToggleFavorite(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiCollectionIdToggleFavoriteMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiCollectionIdToggleFavorite>>
>;

export type PostApiCollectionIdToggleFavoriteMutationError = ErrorType<void>;

export const usePostApiCollectionIdToggleFavorite = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiCollectionIdToggleFavorite>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiCollectionIdToggleFavorite>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getPostApiCollectionIdToggleFavoriteMutationOptions(options),
		queryClient,
	);
};
export const getApiCollectionImagesId = (
	id: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<Blob>(
		{
			url: `/api/collection/images/${id}`,
			method: "GET",
			responseType: "blob",
			signal,
		},
		options,
	);
};

export const getGetApiCollectionImagesIdQueryKey = (id: string) => {
	return [`/api/collection/images/${id}`] as const;
};

export const getGetApiCollectionImagesIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiCollectionImagesId>>,
	TError = ErrorType<void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionImagesId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiCollectionImagesIdQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiCollectionImagesId>>
	> = ({ signal }) => getApiCollectionImagesId(id, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiCollectionImagesId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiCollectionImagesIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiCollectionImagesId>>
>;
export type GetApiCollectionImagesIdQueryError = ErrorType<void>;

export function useGetApiCollectionImagesId<
	TData = Awaited<ReturnType<typeof getApiCollectionImagesId>>,
	TError = ErrorType<void>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionImagesId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiCollectionImagesId>>,
					TError,
					Awaited<ReturnType<typeof getApiCollectionImagesId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCollectionImagesId<
	TData = Awaited<ReturnType<typeof getApiCollectionImagesId>>,
	TError = ErrorType<void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionImagesId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiCollectionImagesId>>,
					TError,
					Awaited<ReturnType<typeof getApiCollectionImagesId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCollectionImagesId<
	TData = Awaited<ReturnType<typeof getApiCollectionImagesId>>,
	TError = ErrorType<void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionImagesId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiCollectionImagesId<
	TData = Awaited<ReturnType<typeof getApiCollectionImagesId>>,
	TError = ErrorType<void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionImagesId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiCollectionImagesIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getApiCollectionIdSpheres = (
	id: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CollectionEntrySpherePerks>(
		{ url: `/api/collection/${id}/spheres`, method: "GET", signal },
		options,
	);
};

export const getGetApiCollectionIdSpheresQueryKey = (id: string) => {
	return [`/api/collection/${id}/spheres`] as const;
};

export const getGetApiCollectionIdSpheresQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
	TError = ErrorType<void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiCollectionIdSpheresQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiCollectionIdSpheres>>
	> = ({ signal }) => getApiCollectionIdSpheres(id, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiCollectionIdSpheresQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiCollectionIdSpheres>>
>;
export type GetApiCollectionIdSpheresQueryError = ErrorType<void>;

export function useGetApiCollectionIdSpheres<
	TData = Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
	TError = ErrorType<void>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
					TError,
					Awaited<ReturnType<typeof getApiCollectionIdSpheres>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCollectionIdSpheres<
	TData = Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
	TError = ErrorType<void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
					TError,
					Awaited<ReturnType<typeof getApiCollectionIdSpheres>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCollectionIdSpheres<
	TData = Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
	TError = ErrorType<void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiCollectionIdSpheres<
	TData = Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
	TError = ErrorType<void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiCollectionIdSpheres>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiCollectionIdSpheresQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiCollectionIdSpheres = (
	id: string,
	collectionEntrySpherePerks: BodyType<CollectionEntrySpherePerks>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UpdateResponse>(
		{
			url: `/api/collection/${id}/spheres`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: collectionEntrySpherePerks,
			signal,
		},
		options,
	);
};

export const getPostApiCollectionIdSpheresMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiCollectionIdSpheres>>,
		TError,
		{ id: string; data: BodyType<CollectionEntrySpherePerks> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiCollectionIdSpheres>>,
	TError,
	{ id: string; data: BodyType<CollectionEntrySpherePerks> },
	TContext
> => {
	const mutationKey = ["postApiCollectionIdSpheres"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiCollectionIdSpheres>>,
		{ id: string; data: BodyType<CollectionEntrySpherePerks> }
	> = (props) => {
		const { id, data } = props ?? {};

		return postApiCollectionIdSpheres(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiCollectionIdSpheresMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiCollectionIdSpheres>>
>;
export type PostApiCollectionIdSpheresMutationBody =
	BodyType<CollectionEntrySpherePerks>;
export type PostApiCollectionIdSpheresMutationError = ErrorType<void>;

export const usePostApiCollectionIdSpheres = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiCollectionIdSpheres>>,
			TError,
			{ id: string; data: BodyType<CollectionEntrySpherePerks> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiCollectionIdSpheres>>,
	TError,
	{ id: string; data: BodyType<CollectionEntrySpherePerks> },
	TContext
> => {
	return useMutation(
		getPostApiCollectionIdSpheresMutationOptions(options),
		queryClient,
	);
};
