/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AddCharacterRequest {
	name: string;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	rank?: number | string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	claims?: number | string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	images?: number | string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	gifs?: number | string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	seriesCount?: number | string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	keyCount?: number | string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	kakera?: number | string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	sp?: number | string | null;
	/** @nullable */
	imageUrl?: string | null;
	/** @nullable */
	seriesName?: string | null;
}
