/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from "./userDto";

export interface AuthResponse {
	accessToken: string;
	refreshToken: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	expiresIn: number | string;
	user: UserDto;
}
