/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CalculatorConfigDto {
	id: string;
	name: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalPool: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	disabledLimit: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	antiDisabled: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	silverBadge: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	rubyBadge: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	bwLevel: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	perk2: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	perk3: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	perk4: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	ownedTotal: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	ownedDisabled: number | string;
	createdAt: string;
	updatedAt: string;
}
