/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CharacterDto } from "./characterDto";

export interface CollectionEntryDto {
	id: string;
	character: CharacterDto;
	/** @nullable */
	acquiredAt: string | null;
	/** @nullable */
	notes: string | null;
	isDisabled?: boolean;
	isFavorite?: boolean;
}
