/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CollectionExportItemDto {
	name: string;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	kakera: number | string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	keyCount: number | string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	sp: number | string | null;
	isDisabled: boolean;
}
