/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CollectionStatsDtoKeyDistribution } from "./collectionStatsDtoKeyDistribution";

export interface CollectionStatsDto {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalCharacters: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalKakera: number | string;
	keyDistribution: CollectionStatsDtoKeyDistribution;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	disabledCount?: number | string;
}
