/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { KakeraType } from "./kakeraType";

export interface CreateKakeraClaimRequest {
	/** @nullable */
	characterId: string | null;
	/** @nullable */
	characterName: string | null;
	type: KakeraType;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	value: number | string;
	isClaimed: boolean;
	/** @nullable */
	claimedAt: string | null;
}
