/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateWishlistEntryRequest {
	characterId: string;
	isStarwish?: boolean;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	priority?: number | string;
	/** @nullable */
	notes?: string | null;
}
