/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface DeleteClaimsResponse {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	deleted: number | string;
}
