/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface EnableListDto {
	id: string;
	name: string;
	content: string;
	isActive: boolean;
	createdAt: string;
	updatedAt: string;
}
