/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SafeFileHandle } from "./safeFileHandle";

export interface FileStream {
	handle?: unknown;
	canRead?: boolean;
	canWrite?: boolean;
	safeFileHandle?: SafeFileHandle;
	/** @nullable */
	name?: string | null;
	isAsync?: boolean;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	length?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	position?: number | string;
	canSeek?: boolean;
	canTimeout?: boolean;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	readTimeout?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	writeTimeout?: number | string;
}
