/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ImportClaimsResponse {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	imported: number | string;
}
