/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OptimizerAnalysisResponseKeyDistribution } from "./optimizerAnalysisResponseKeyDistribution";
import type { OptimizerRecommendation } from "./optimizerRecommendation";

export interface OptimizerAnalysisResponse {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalCharacters: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalKakera: number | string;
	keyDistribution: OptimizerAnalysisResponseKeyDistribution;
	recommendations: OptimizerRecommendation[];
}
