/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface OptimizerSuggestionDto {
	id: string;
	type: string;
	characters: string[];
	reason: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	priority: number | string;
}
