/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { WishlistEntryDto } from "./wishlistEntryDto";

export interface PaginatedWishlistResponse {
	items: WishlistEntryDto[];
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	total: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	page: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	pageSize: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalPages: number | string;
}
