/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateListRequest {
	/** @nullable */
	name: string | null;
	/** @nullable */
	content: string | null;
	/** @nullable */
	isActive: boolean | null;
}
