/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UserProfileDto {
	id: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	bronzeBadge: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	silverBadge: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	goldBadge: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	sapphireBadge: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	rubyBadge: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	emeraldBadge: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	diamondBadge: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk1: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk2: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk3: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk4: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk5: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk6: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk7: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk8: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk9: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk10: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk11: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	towerPerk12: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalPool: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	disabledLimit: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	antiDisabled: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalRolls: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	bwRollsInvested: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	kakeraPerFloor: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	bronzeBadgePrice: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	silverBadgePrice: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	goldBadgePrice: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	sapphireBadgePrice: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	rubyBadgePrice: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	emeraldBadgePrice: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	diamondBadgePrice: number | string;
	createdAt: string;
	updatedAt: string;
}
