/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface WishlistStatsDto {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalCount: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	starwishCount: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	regularCount: number | string;
}
