/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";

import type {
	CreateListRequest,
	CreateWishlistEntryRequest,
	ExportRequest,
	GetApiListsPresetsParams,
	GetApiListsWishlistParams,
	UpdateListRequest,
	UpdateWishlistEntryRequest,
} from "../model";

export const getApiListsEnable = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.get(`/api/lists/enable`, options);
};

export const getGetApiListsEnableQueryKey = () => {
	return [`/api/lists/enable`] as const;
};

export const getGetApiListsEnableQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiListsEnable>>,
	TError = AxiosError<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getApiListsEnable>>,
			TError,
			TData
		>
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiListsEnableQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiListsEnable>>
	> = ({ signal }) => getApiListsEnable({ signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiListsEnable>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiListsEnableQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiListsEnable>>
>;
export type GetApiListsEnableQueryError = AxiosError<unknown>;

export function useGetApiListsEnable<
	TData = Awaited<ReturnType<typeof getApiListsEnable>>,
	TError = AxiosError<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsEnable>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiListsEnable>>,
					TError,
					Awaited<ReturnType<typeof getApiListsEnable>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiListsEnable<
	TData = Awaited<ReturnType<typeof getApiListsEnable>>,
	TError = AxiosError<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsEnable>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiListsEnable>>,
					TError,
					Awaited<ReturnType<typeof getApiListsEnable>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiListsEnable<
	TData = Awaited<ReturnType<typeof getApiListsEnable>>,
	TError = AxiosError<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsEnable>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiListsEnable<
	TData = Awaited<ReturnType<typeof getApiListsEnable>>,
	TError = AxiosError<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsEnable>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiListsEnableQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiListsEnable = (
	createListRequest: CreateListRequest,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.post(`/api/lists/enable`, createListRequest, options);
};

export const getPostApiListsEnableMutationOptions = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiListsEnable>>,
		TError,
		{ data: CreateListRequest },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiListsEnable>>,
	TError,
	{ data: CreateListRequest },
	TContext
> => {
	const mutationKey = ["postApiListsEnable"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiListsEnable>>,
		{ data: CreateListRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postApiListsEnable(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiListsEnableMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiListsEnable>>
>;
export type PostApiListsEnableMutationBody = CreateListRequest;
export type PostApiListsEnableMutationError = AxiosError<unknown>;

export const usePostApiListsEnable = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiListsEnable>>,
			TError,
			{ data: CreateListRequest },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiListsEnable>>,
	TError,
	{ data: CreateListRequest },
	TContext
> => {
	return useMutation(
		getPostApiListsEnableMutationOptions(options),
		queryClient,
	);
};
export const getApiListsDisable = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.get(`/api/lists/disable`, options);
};

export const getGetApiListsDisableQueryKey = () => {
	return [`/api/lists/disable`] as const;
};

export const getGetApiListsDisableQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiListsDisable>>,
	TError = AxiosError<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getApiListsDisable>>,
			TError,
			TData
		>
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiListsDisableQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiListsDisable>>
	> = ({ signal }) => getApiListsDisable({ signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiListsDisable>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiListsDisableQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiListsDisable>>
>;
export type GetApiListsDisableQueryError = AxiosError<unknown>;

export function useGetApiListsDisable<
	TData = Awaited<ReturnType<typeof getApiListsDisable>>,
	TError = AxiosError<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsDisable>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiListsDisable>>,
					TError,
					Awaited<ReturnType<typeof getApiListsDisable>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiListsDisable<
	TData = Awaited<ReturnType<typeof getApiListsDisable>>,
	TError = AxiosError<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsDisable>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiListsDisable>>,
					TError,
					Awaited<ReturnType<typeof getApiListsDisable>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiListsDisable<
	TData = Awaited<ReturnType<typeof getApiListsDisable>>,
	TError = AxiosError<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsDisable>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiListsDisable<
	TData = Awaited<ReturnType<typeof getApiListsDisable>>,
	TError = AxiosError<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsDisable>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiListsDisableQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiListsDisable = (
	createListRequest: CreateListRequest,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.post(`/api/lists/disable`, createListRequest, options);
};

export const getPostApiListsDisableMutationOptions = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiListsDisable>>,
		TError,
		{ data: CreateListRequest },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiListsDisable>>,
	TError,
	{ data: CreateListRequest },
	TContext
> => {
	const mutationKey = ["postApiListsDisable"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiListsDisable>>,
		{ data: CreateListRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postApiListsDisable(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiListsDisableMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiListsDisable>>
>;
export type PostApiListsDisableMutationBody = CreateListRequest;
export type PostApiListsDisableMutationError = AxiosError<unknown>;

export const usePostApiListsDisable = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiListsDisable>>,
			TError,
			{ data: CreateListRequest },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiListsDisable>>,
	TError,
	{ data: CreateListRequest },
	TContext
> => {
	return useMutation(
		getPostApiListsDisableMutationOptions(options),
		queryClient,
	);
};
export const putApiListsTypeId = (
	type: string,
	id: string,
	updateListRequest: UpdateListRequest,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.put(
		`/api/lists/${type}/${id}`,
		updateListRequest,
		options,
	);
};

export const getPutApiListsTypeIdMutationOptions = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putApiListsTypeId>>,
		TError,
		{ type: string; id: string; data: UpdateListRequest },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putApiListsTypeId>>,
	TError,
	{ type: string; id: string; data: UpdateListRequest },
	TContext
> => {
	const mutationKey = ["putApiListsTypeId"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putApiListsTypeId>>,
		{ type: string; id: string; data: UpdateListRequest }
	> = (props) => {
		const { type, id, data } = props ?? {};

		return putApiListsTypeId(type, id, data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutApiListsTypeIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof putApiListsTypeId>>
>;
export type PutApiListsTypeIdMutationBody = UpdateListRequest;
export type PutApiListsTypeIdMutationError = AxiosError<unknown>;

export const usePutApiListsTypeId = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putApiListsTypeId>>,
			TError,
			{ type: string; id: string; data: UpdateListRequest },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putApiListsTypeId>>,
	TError,
	{ type: string; id: string; data: UpdateListRequest },
	TContext
> => {
	return useMutation(getPutApiListsTypeIdMutationOptions(options), queryClient);
};
export const deleteApiListsTypeId = (
	type: string,
	id: string,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.delete(`/api/lists/${type}/${id}`, options);
};

export const getDeleteApiListsTypeIdMutationOptions = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteApiListsTypeId>>,
		TError,
		{ type: string; id: string },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteApiListsTypeId>>,
	TError,
	{ type: string; id: string },
	TContext
> => {
	const mutationKey = ["deleteApiListsTypeId"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteApiListsTypeId>>,
		{ type: string; id: string }
	> = (props) => {
		const { type, id } = props ?? {};

		return deleteApiListsTypeId(type, id, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteApiListsTypeIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiListsTypeId>>
>;

export type DeleteApiListsTypeIdMutationError = AxiosError<unknown>;

export const useDeleteApiListsTypeId = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteApiListsTypeId>>,
			TError,
			{ type: string; id: string },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteApiListsTypeId>>,
	TError,
	{ type: string; id: string },
	TContext
> => {
	return useMutation(
		getDeleteApiListsTypeIdMutationOptions(options),
		queryClient,
	);
};
export const getApiListsPresets = (
	params?: GetApiListsPresetsParams,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.get(`/api/lists/presets`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetApiListsPresetsQueryKey = (
	params?: GetApiListsPresetsParams,
) => {
	return [`/api/lists/presets`, ...(params ? [params] : [])] as const;
};

export const getGetApiListsPresetsQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiListsPresets>>,
	TError = AxiosError<unknown>,
>(
	params?: GetApiListsPresetsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsPresets>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiListsPresetsQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiListsPresets>>
	> = ({ signal }) => getApiListsPresets(params, { signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiListsPresets>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiListsPresetsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiListsPresets>>
>;
export type GetApiListsPresetsQueryError = AxiosError<unknown>;

export function useGetApiListsPresets<
	TData = Awaited<ReturnType<typeof getApiListsPresets>>,
	TError = AxiosError<unknown>,
>(
	params: undefined | GetApiListsPresetsParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsPresets>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiListsPresets>>,
					TError,
					Awaited<ReturnType<typeof getApiListsPresets>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiListsPresets<
	TData = Awaited<ReturnType<typeof getApiListsPresets>>,
	TError = AxiosError<unknown>,
>(
	params?: GetApiListsPresetsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsPresets>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiListsPresets>>,
					TError,
					Awaited<ReturnType<typeof getApiListsPresets>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiListsPresets<
	TData = Awaited<ReturnType<typeof getApiListsPresets>>,
	TError = AxiosError<unknown>,
>(
	params?: GetApiListsPresetsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsPresets>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiListsPresets<
	TData = Awaited<ReturnType<typeof getApiListsPresets>>,
	TError = AxiosError<unknown>,
>(
	params?: GetApiListsPresetsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsPresets>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiListsPresetsQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiListsExport = (
	exportRequest: ExportRequest,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.post(`/api/lists/export`, exportRequest, options);
};

export const getPostApiListsExportMutationOptions = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiListsExport>>,
		TError,
		{ data: ExportRequest },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiListsExport>>,
	TError,
	{ data: ExportRequest },
	TContext
> => {
	const mutationKey = ["postApiListsExport"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiListsExport>>,
		{ data: ExportRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postApiListsExport(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiListsExportMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiListsExport>>
>;
export type PostApiListsExportMutationBody = ExportRequest;
export type PostApiListsExportMutationError = AxiosError<unknown>;

export const usePostApiListsExport = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiListsExport>>,
			TError,
			{ data: ExportRequest },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiListsExport>>,
	TError,
	{ data: ExportRequest },
	TContext
> => {
	return useMutation(
		getPostApiListsExportMutationOptions(options),
		queryClient,
	);
};
export const getApiListsWishlist = (
	params?: GetApiListsWishlistParams,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.get(`/api/lists/wishlist`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetApiListsWishlistQueryKey = (
	params?: GetApiListsWishlistParams,
) => {
	return [`/api/lists/wishlist`, ...(params ? [params] : [])] as const;
};

export const getGetApiListsWishlistQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiListsWishlist>>,
	TError = AxiosError<unknown>,
>(
	params?: GetApiListsWishlistParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsWishlist>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiListsWishlistQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiListsWishlist>>
	> = ({ signal }) => getApiListsWishlist(params, { signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiListsWishlist>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiListsWishlistQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiListsWishlist>>
>;
export type GetApiListsWishlistQueryError = AxiosError<unknown>;

export function useGetApiListsWishlist<
	TData = Awaited<ReturnType<typeof getApiListsWishlist>>,
	TError = AxiosError<unknown>,
>(
	params: undefined | GetApiListsWishlistParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsWishlist>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiListsWishlist>>,
					TError,
					Awaited<ReturnType<typeof getApiListsWishlist>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiListsWishlist<
	TData = Awaited<ReturnType<typeof getApiListsWishlist>>,
	TError = AxiosError<unknown>,
>(
	params?: GetApiListsWishlistParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsWishlist>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiListsWishlist>>,
					TError,
					Awaited<ReturnType<typeof getApiListsWishlist>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiListsWishlist<
	TData = Awaited<ReturnType<typeof getApiListsWishlist>>,
	TError = AxiosError<unknown>,
>(
	params?: GetApiListsWishlistParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsWishlist>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiListsWishlist<
	TData = Awaited<ReturnType<typeof getApiListsWishlist>>,
	TError = AxiosError<unknown>,
>(
	params?: GetApiListsWishlistParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsWishlist>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiListsWishlistQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiListsWishlist = (
	createWishlistEntryRequest: CreateWishlistEntryRequest,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.post(
		`/api/lists/wishlist`,
		createWishlistEntryRequest,
		options,
	);
};

export const getPostApiListsWishlistMutationOptions = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiListsWishlist>>,
		TError,
		{ data: CreateWishlistEntryRequest },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiListsWishlist>>,
	TError,
	{ data: CreateWishlistEntryRequest },
	TContext
> => {
	const mutationKey = ["postApiListsWishlist"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiListsWishlist>>,
		{ data: CreateWishlistEntryRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postApiListsWishlist(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiListsWishlistMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiListsWishlist>>
>;
export type PostApiListsWishlistMutationBody = CreateWishlistEntryRequest;
export type PostApiListsWishlistMutationError = AxiosError<unknown>;

export const usePostApiListsWishlist = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiListsWishlist>>,
			TError,
			{ data: CreateWishlistEntryRequest },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiListsWishlist>>,
	TError,
	{ data: CreateWishlistEntryRequest },
	TContext
> => {
	return useMutation(
		getPostApiListsWishlistMutationOptions(options),
		queryClient,
	);
};
export const getApiListsWishlistStats = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.get(`/api/lists/wishlist/stats`, options);
};

export const getGetApiListsWishlistStatsQueryKey = () => {
	return [`/api/lists/wishlist/stats`] as const;
};

export const getGetApiListsWishlistStatsQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiListsWishlistStats>>,
	TError = AxiosError<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getApiListsWishlistStats>>,
			TError,
			TData
		>
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiListsWishlistStatsQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiListsWishlistStats>>
	> = ({ signal }) => getApiListsWishlistStats({ signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiListsWishlistStats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiListsWishlistStatsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiListsWishlistStats>>
>;
export type GetApiListsWishlistStatsQueryError = AxiosError<unknown>;

export function useGetApiListsWishlistStats<
	TData = Awaited<ReturnType<typeof getApiListsWishlistStats>>,
	TError = AxiosError<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsWishlistStats>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiListsWishlistStats>>,
					TError,
					Awaited<ReturnType<typeof getApiListsWishlistStats>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiListsWishlistStats<
	TData = Awaited<ReturnType<typeof getApiListsWishlistStats>>,
	TError = AxiosError<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsWishlistStats>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiListsWishlistStats>>,
					TError,
					Awaited<ReturnType<typeof getApiListsWishlistStats>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiListsWishlistStats<
	TData = Awaited<ReturnType<typeof getApiListsWishlistStats>>,
	TError = AxiosError<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsWishlistStats>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiListsWishlistStats<
	TData = Awaited<ReturnType<typeof getApiListsWishlistStats>>,
	TError = AxiosError<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiListsWishlistStats>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiListsWishlistStatsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const putApiListsWishlistId = (
	id: string,
	updateWishlistEntryRequest: UpdateWishlistEntryRequest,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.put(
		`/api/lists/wishlist/${id}`,
		updateWishlistEntryRequest,
		options,
	);
};

export const getPutApiListsWishlistIdMutationOptions = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putApiListsWishlistId>>,
		TError,
		{ id: string; data: UpdateWishlistEntryRequest },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putApiListsWishlistId>>,
	TError,
	{ id: string; data: UpdateWishlistEntryRequest },
	TContext
> => {
	const mutationKey = ["putApiListsWishlistId"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putApiListsWishlistId>>,
		{ id: string; data: UpdateWishlistEntryRequest }
	> = (props) => {
		const { id, data } = props ?? {};

		return putApiListsWishlistId(id, data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutApiListsWishlistIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof putApiListsWishlistId>>
>;
export type PutApiListsWishlistIdMutationBody = UpdateWishlistEntryRequest;
export type PutApiListsWishlistIdMutationError = AxiosError<unknown>;

export const usePutApiListsWishlistId = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putApiListsWishlistId>>,
			TError,
			{ id: string; data: UpdateWishlistEntryRequest },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putApiListsWishlistId>>,
	TError,
	{ id: string; data: UpdateWishlistEntryRequest },
	TContext
> => {
	return useMutation(
		getPutApiListsWishlistIdMutationOptions(options),
		queryClient,
	);
};
export const deleteApiListsWishlistId = (
	id: string,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.delete(`/api/lists/wishlist/${id}`, options);
};

export const getDeleteApiListsWishlistIdMutationOptions = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteApiListsWishlistId>>,
		TError,
		{ id: string },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteApiListsWishlistId>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["deleteApiListsWishlistId"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteApiListsWishlistId>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return deleteApiListsWishlistId(id, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteApiListsWishlistIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiListsWishlistId>>
>;

export type DeleteApiListsWishlistIdMutationError = AxiosError<unknown>;

export const useDeleteApiListsWishlistId = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteApiListsWishlistId>>,
			TError,
			{ id: string },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteApiListsWishlistId>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getDeleteApiListsWishlistIdMutationOptions(options),
		queryClient,
	);
};
export const postApiListsWishlistToggleStarwishId = (
	id: string,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	return axios.default.post(
		`/api/lists/wishlist/toggle-starwish/${id}`,
		undefined,
		options,
	);
};

export const getPostApiListsWishlistToggleStarwishIdMutationOptions = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiListsWishlistToggleStarwishId>>,
		TError,
		{ id: string },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiListsWishlistToggleStarwishId>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["postApiListsWishlistToggleStarwishId"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiListsWishlistToggleStarwishId>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return postApiListsWishlistToggleStarwishId(id, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiListsWishlistToggleStarwishIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiListsWishlistToggleStarwishId>>
>;

export type PostApiListsWishlistToggleStarwishIdMutationError =
	AxiosError<unknown>;

export const usePostApiListsWishlistToggleStarwishId = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiListsWishlistToggleStarwishId>>,
			TError,
			{ id: string },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiListsWishlistToggleStarwishId>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getPostApiListsWishlistToggleStarwishIdMutationOptions(options),
		queryClient,
	);
};
