/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.Mutils.Api | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { BodyType, ErrorType } from "../../lib/custom-instance";

import { customInstance } from "../../lib/custom-instance";
import type {
	AuthErrorResponse,
	AuthResponse,
	GetApiAuthCallbackParams,
	RefreshTokenRequest,
	RefreshTokenResponse,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getApiAuthDiscord = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<unknown>(
		{ url: `/api/auth/discord`, method: "GET", signal },
		options,
	);
};

export const getGetApiAuthDiscordQueryKey = () => {
	return [`/api/auth/discord`] as const;
};

export const getGetApiAuthDiscordQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiAuthDiscord>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getApiAuthDiscord>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiAuthDiscordQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiAuthDiscord>>
	> = ({ signal }) => getApiAuthDiscord(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiAuthDiscord>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthDiscordQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiAuthDiscord>>
>;
export type GetApiAuthDiscordQueryError = ErrorType<void>;

export function useGetApiAuthDiscord<
	TData = Awaited<ReturnType<typeof getApiAuthDiscord>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiAuthDiscord>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthDiscord>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthDiscord>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthDiscord<
	TData = Awaited<ReturnType<typeof getApiAuthDiscord>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiAuthDiscord>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthDiscord>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthDiscord>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthDiscord<
	TData = Awaited<ReturnType<typeof getApiAuthDiscord>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiAuthDiscord>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiAuthDiscord<
	TData = Awaited<ReturnType<typeof getApiAuthDiscord>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiAuthDiscord>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiAuthDiscordQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getApiAuthCallback = (
	params?: GetApiAuthCallbackParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AuthResponse>(
		{ url: `/api/auth/callback`, method: "GET", params, signal },
		options,
	);
};

export const getGetApiAuthCallbackQueryKey = (
	params?: GetApiAuthCallbackParams,
) => {
	return [`/api/auth/callback`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuthCallbackQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiAuthCallback>>,
	TError = ErrorType<AuthErrorResponse>,
>(
	params?: GetApiAuthCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiAuthCallback>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiAuthCallbackQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiAuthCallback>>
	> = ({ signal }) => getApiAuthCallback(params, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiAuthCallback>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthCallbackQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiAuthCallback>>
>;
export type GetApiAuthCallbackQueryError = ErrorType<AuthErrorResponse>;

export function useGetApiAuthCallback<
	TData = Awaited<ReturnType<typeof getApiAuthCallback>>,
	TError = ErrorType<AuthErrorResponse>,
>(
	params: undefined | GetApiAuthCallbackParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiAuthCallback>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthCallback>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthCallback>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthCallback<
	TData = Awaited<ReturnType<typeof getApiAuthCallback>>,
	TError = ErrorType<AuthErrorResponse>,
>(
	params?: GetApiAuthCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiAuthCallback>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthCallback>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthCallback>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthCallback<
	TData = Awaited<ReturnType<typeof getApiAuthCallback>>,
	TError = ErrorType<AuthErrorResponse>,
>(
	params?: GetApiAuthCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiAuthCallback>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiAuthCallback<
	TData = Awaited<ReturnType<typeof getApiAuthCallback>>,
	TError = ErrorType<AuthErrorResponse>,
>(
	params?: GetApiAuthCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiAuthCallback>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiAuthCallbackQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiAuthRefresh = (
	refreshTokenRequest: BodyType<RefreshTokenRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<RefreshTokenResponse>(
		{
			url: `/api/auth/refresh`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: refreshTokenRequest,
			signal,
		},
		options,
	);
};

export const getPostApiAuthRefreshMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiAuthRefresh>>,
		TError,
		{ data: BodyType<RefreshTokenRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiAuthRefresh>>,
	TError,
	{ data: BodyType<RefreshTokenRequest> },
	TContext
> => {
	const mutationKey = ["postApiAuthRefresh"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiAuthRefresh>>,
		{ data: BodyType<RefreshTokenRequest> }
	> = (props) => {
		const { data } = props ?? {};

		return postApiAuthRefresh(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRefreshMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiAuthRefresh>>
>;
export type PostApiAuthRefreshMutationBody = BodyType<RefreshTokenRequest>;
export type PostApiAuthRefreshMutationError = ErrorType<unknown>;

export const usePostApiAuthRefresh = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiAuthRefresh>>,
			TError,
			{ data: BodyType<RefreshTokenRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiAuthRefresh>>,
	TError,
	{ data: BodyType<RefreshTokenRequest> },
	TContext
> => {
	return useMutation(
		getPostApiAuthRefreshMutationOptions(options),
		queryClient,
	);
};
export const postApiAuthLogout = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/auth/logout`, method: "POST", signal },
		options,
	);
};

export const getPostApiAuthLogoutMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiAuthLogout>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiAuthLogout>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["postApiAuthLogout"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiAuthLogout>>,
		void
	> = () => {
		return postApiAuthLogout(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiAuthLogoutMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiAuthLogout>>
>;

export type PostApiAuthLogoutMutationError = ErrorType<unknown>;

export const usePostApiAuthLogout = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiAuthLogout>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiAuthLogout>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getPostApiAuthLogoutMutationOptions(options), queryClient);
};
