/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";

import type {
	GetLiveDataSnapshotsParams,
	PaginatedResultOfLiveDataSnapshotDto,
} from "../model";

/**
 * Get a paginated list of live data snapshots with optional filtering
 */
export const getLiveDataSnapshots = (
	params?: GetLiveDataSnapshotsParams,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PaginatedResultOfLiveDataSnapshotDto>> => {
	return axios.default.get(`/api/livedata`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetLiveDataSnapshotsQueryKey = (
	params?: GetLiveDataSnapshotsParams,
) => {
	return [`/api/livedata`, ...(params ? [params] : [])] as const;
};

export const getGetLiveDataSnapshotsQueryOptions = <
	TData = Awaited<ReturnType<typeof getLiveDataSnapshots>>,
	TError = AxiosError<unknown>,
>(
	params?: GetLiveDataSnapshotsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getLiveDataSnapshots>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetLiveDataSnapshotsQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getLiveDataSnapshots>>
	> = ({ signal }) => getLiveDataSnapshots(params, { signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getLiveDataSnapshots>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLiveDataSnapshotsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getLiveDataSnapshots>>
>;
export type GetLiveDataSnapshotsQueryError = AxiosError<unknown>;

export function useGetLiveDataSnapshots<
	TData = Awaited<ReturnType<typeof getLiveDataSnapshots>>,
	TError = AxiosError<unknown>,
>(
	params: undefined | GetLiveDataSnapshotsParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getLiveDataSnapshots>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getLiveDataSnapshots>>,
					TError,
					Awaited<ReturnType<typeof getLiveDataSnapshots>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLiveDataSnapshots<
	TData = Awaited<ReturnType<typeof getLiveDataSnapshots>>,
	TError = AxiosError<unknown>,
>(
	params?: GetLiveDataSnapshotsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getLiveDataSnapshots>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getLiveDataSnapshots>>,
					TError,
					Awaited<ReturnType<typeof getLiveDataSnapshots>>
				>,
				"initialData"
			>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLiveDataSnapshots<
	TData = Awaited<ReturnType<typeof getLiveDataSnapshots>>,
	TError = AxiosError<unknown>,
>(
	params?: GetLiveDataSnapshotsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getLiveDataSnapshots>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetLiveDataSnapshots<
	TData = Awaited<ReturnType<typeof getLiveDataSnapshots>>,
	TError = AxiosError<unknown>,
>(
	params?: GetLiveDataSnapshotsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getLiveDataSnapshots>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetLiveDataSnapshotsQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
