<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BlurHashSharp" />
        <PackageReference Include="DotNetEnv" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Minio" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="SixLabors.ImageSharp" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Archive.DB\Shiron.TheArchive.DB.csproj" />
        <ProjectReference Include="..\Lib.Types.Extension\Shiron.Lib.Types.Extension.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="DTOs\" />
    </ItemGroup>
</Project>
