/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.ResonanceSystem.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EchoInstanceDTO } from "./echoInstanceDTO";

export interface CreateCharacterInstanceDTO {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	characterID: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	sequenceChain: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	level: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	forte0Level: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	forte1Level: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	forte2Level: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	forte3Level: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	forte4Level: number | string;
	echoes?: EchoInstanceDTO[];
}
