/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.ResonanceSystem.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EchoDTO } from "./echoDTO";

export interface EchoSonataDTO {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	id: number | string;
	name: string;
	echoes: EchoDTO[];
}
