/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.ResonanceSystem.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IFormFile } from "./iFormFile";

export type PostApiScanWuwaBotBody = {
	file: IFormFile;
};
