/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.ResonanceSystem.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UserInfoDto {
	id?: string;
	displayName?: string;
	userName?: string;
	email?: string;
	roles?: string[];
}
