/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.ResonanceSystem.API | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	CharacterInstanceDTO,
	CreateCharacterInstanceDTO,
	EchoInstanceDTO,
} from "../model";

export type postApiInventoryResonatorResponse200 = {
	data: void;
	status: 200;
};

export type postApiInventoryResonatorResponseSuccess =
	postApiInventoryResonatorResponse200 & {
		headers: Headers;
	};

export type postApiInventoryResonatorResponse =
	postApiInventoryResonatorResponseSuccess;

export const getPostApiInventoryResonatorUrl = () => {
	return `/api/inventory/resonator`;
};

export const postApiInventoryResonator = async (
	createCharacterInstanceDTO: CreateCharacterInstanceDTO,
	options?: RequestInit,
): Promise<postApiInventoryResonatorResponse> => {
	const res = await fetch(getPostApiInventoryResonatorUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(createCharacterInstanceDTO),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: postApiInventoryResonatorResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as postApiInventoryResonatorResponse;
};

export const getPostApiInventoryResonatorMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiInventoryResonator>>,
		TError,
		{ data: CreateCharacterInstanceDTO },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiInventoryResonator>>,
	TError,
	{ data: CreateCharacterInstanceDTO },
	TContext
> => {
	const mutationKey = ["postApiInventoryResonator"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiInventoryResonator>>,
		{ data: CreateCharacterInstanceDTO }
	> = (props) => {
		const { data } = props ?? {};

		return postApiInventoryResonator(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiInventoryResonatorMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiInventoryResonator>>
>;
export type PostApiInventoryResonatorMutationBody = CreateCharacterInstanceDTO;
export type PostApiInventoryResonatorMutationError = unknown;

export const usePostApiInventoryResonator = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiInventoryResonator>>,
			TError,
			{ data: CreateCharacterInstanceDTO },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiInventoryResonator>>,
	TError,
	{ data: CreateCharacterInstanceDTO },
	TContext
> => {
	return useMutation(
		getPostApiInventoryResonatorMutationOptions(options),
		queryClient,
	);
};
export type getApiInventoryResonatorsResponse200 = {
	data: CharacterInstanceDTO[];
	status: 200;
};

export type getApiInventoryResonatorsResponseSuccess =
	getApiInventoryResonatorsResponse200 & {
		headers: Headers;
	};

export type getApiInventoryResonatorsResponse =
	getApiInventoryResonatorsResponseSuccess;

export const getGetApiInventoryResonatorsUrl = () => {
	return `/api/inventory/resonators`;
};

export const getApiInventoryResonators = async (
	options?: RequestInit,
): Promise<getApiInventoryResonatorsResponse> => {
	const res = await fetch(getGetApiInventoryResonatorsUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiInventoryResonatorsResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiInventoryResonatorsResponse;
};

export const getGetApiInventoryResonatorsQueryKey = () => {
	return [`/api/inventory/resonators`] as const;
};

export const getGetApiInventoryResonatorsQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiInventoryResonators>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getApiInventoryResonators>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiInventoryResonatorsQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiInventoryResonators>>
	> = ({ signal }) => getApiInventoryResonators({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiInventoryResonators>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiInventoryResonatorsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiInventoryResonators>>
>;
export type GetApiInventoryResonatorsQueryError = unknown;

export function useGetApiInventoryResonators<
	TData = Awaited<ReturnType<typeof getApiInventoryResonators>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiInventoryResonators>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiInventoryResonators>>,
					TError,
					Awaited<ReturnType<typeof getApiInventoryResonators>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiInventoryResonators<
	TData = Awaited<ReturnType<typeof getApiInventoryResonators>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiInventoryResonators>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiInventoryResonators>>,
					TError,
					Awaited<ReturnType<typeof getApiInventoryResonators>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiInventoryResonators<
	TData = Awaited<ReturnType<typeof getApiInventoryResonators>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiInventoryResonators>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiInventoryResonators<
	TData = Awaited<ReturnType<typeof getApiInventoryResonators>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiInventoryResonators>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiInventoryResonatorsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiInventoryResonatorsIdResponse200 = {
	data: CharacterInstanceDTO;
	status: 200;
};

export type getApiInventoryResonatorsIdResponseSuccess =
	getApiInventoryResonatorsIdResponse200 & {
		headers: Headers;
	};

export type getApiInventoryResonatorsIdResponse =
	getApiInventoryResonatorsIdResponseSuccess;

export const getGetApiInventoryResonatorsIdUrl = (id: string) => {
	return `/api/inventory/resonators/${id}`;
};

export const getApiInventoryResonatorsId = async (
	id: string,
	options?: RequestInit,
): Promise<getApiInventoryResonatorsIdResponse> => {
	const res = await fetch(getGetApiInventoryResonatorsIdUrl(id), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiInventoryResonatorsIdResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiInventoryResonatorsIdResponse;
};

export const getGetApiInventoryResonatorsIdQueryKey = (id: string) => {
	return [`/api/inventory/resonators/${id}`] as const;
};

export const getGetApiInventoryResonatorsIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiInventoryResonatorsIdQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiInventoryResonatorsId>>
	> = ({ signal }) =>
		getApiInventoryResonatorsId(id, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiInventoryResonatorsIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiInventoryResonatorsId>>
>;
export type GetApiInventoryResonatorsIdQueryError = unknown;

export function useGetApiInventoryResonatorsId<
	TData = Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
	TError = unknown,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
					TError,
					Awaited<ReturnType<typeof getApiInventoryResonatorsId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiInventoryResonatorsId<
	TData = Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
					TError,
					Awaited<ReturnType<typeof getApiInventoryResonatorsId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiInventoryResonatorsId<
	TData = Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiInventoryResonatorsId<
	TData = Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiInventoryResonatorsId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiInventoryResonatorsIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type postApiInventoryResonatorsIdEchoesResponse200 = {
	data: void;
	status: 200;
};

export type postApiInventoryResonatorsIdEchoesResponseSuccess =
	postApiInventoryResonatorsIdEchoesResponse200 & {
		headers: Headers;
	};

export type postApiInventoryResonatorsIdEchoesResponse =
	postApiInventoryResonatorsIdEchoesResponseSuccess;

export const getPostApiInventoryResonatorsIdEchoesUrl = (id: string) => {
	return `/api/inventory/resonators/${id}/echoes`;
};

export const postApiInventoryResonatorsIdEchoes = async (
	id: string,
	echoInstanceDTO: EchoInstanceDTO[],
	options?: RequestInit,
): Promise<postApiInventoryResonatorsIdEchoesResponse> => {
	const res = await fetch(getPostApiInventoryResonatorsIdEchoesUrl(id), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(echoInstanceDTO),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: postApiInventoryResonatorsIdEchoesResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as postApiInventoryResonatorsIdEchoesResponse;
};

export const getPostApiInventoryResonatorsIdEchoesMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiInventoryResonatorsIdEchoes>>,
		TError,
		{ id: string; data: EchoInstanceDTO[] },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiInventoryResonatorsIdEchoes>>,
	TError,
	{ id: string; data: EchoInstanceDTO[] },
	TContext
> => {
	const mutationKey = ["postApiInventoryResonatorsIdEchoes"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiInventoryResonatorsIdEchoes>>,
		{ id: string; data: EchoInstanceDTO[] }
	> = (props) => {
		const { id, data } = props ?? {};

		return postApiInventoryResonatorsIdEchoes(id, data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiInventoryResonatorsIdEchoesMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiInventoryResonatorsIdEchoes>>
>;
export type PostApiInventoryResonatorsIdEchoesMutationBody = EchoInstanceDTO[];
export type PostApiInventoryResonatorsIdEchoesMutationError = unknown;

export const usePostApiInventoryResonatorsIdEchoes = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiInventoryResonatorsIdEchoes>>,
			TError,
			{ id: string; data: EchoInstanceDTO[] },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiInventoryResonatorsIdEchoes>>,
	TError,
	{ id: string; data: EchoInstanceDTO[] },
	TContext
> => {
	return useMutation(
		getPostApiInventoryResonatorsIdEchoesMutationOptions(options),
		queryClient,
	);
};
