/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.HonamiSystem.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AgentPersonaResponse {
	id: string;
	name: string;
	/** @nullable */
	brief: string | null;
	/** @nullable */
	speakingStyle: string | null;
}
