/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.HonamiSystem.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordDto {
	currentPassword: string;
	/** @minLength 4 */
	newPassword: string;
}
