/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.HonamiSystem.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ChatResponse {
	id: string;
	title: string;
	/** @nullable */
	description: string | null;
	/** @nullable */
	groupId: string | null;
	createdAt: string;
	updatedAt: string;
}
