/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.HonamiSystem.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePersonaRequest {
	/**
	 * @maxLength 64
	 * @nullable
	 */
	name?: string | null;
	/**
	 * @maxLength 256
	 * @nullable
	 */
	brief?: string | null;
	/**
	 * @maxLength 8192
	 * @nullable
	 */
	instruction?: string | null;
	/** @nullable */
	traits?: string[] | null;
	/**
	 * @maxLength 512
	 * @nullable
	 */
	speakingStyle?: string | null;
}
