/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.HonamiSystem.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateChatRequest {
	/**
	 * @maxLength 64
	 * @nullable
	 */
	title?: string | null;
	/**
	 * @maxLength 256
	 * @nullable
	 */
	description?: string | null;
}
