/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

import type { RequestHandlerOptions } from "msw";
import { HttpResponse, http } from "msw";

export const getGetDashboardMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/dashboard",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetAnalyticsOverviewMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/overview",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetPerformanceTrendMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/trend",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetTopPlayedMapsMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/maps/top-played",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetBestPerformingMapsMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/maps/best-performing",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetDifficultyStatsMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/difficulty-stats",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetMapTypeStatsMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/map-type-stats",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetScoreDistributionMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/score-distribution",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetHourlyPlayStatsMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/hourly-stats",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetDailyPlayStatsMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/daily-stats",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetAccuracyDistributionMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/analytics/accuracy-distribution",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};
export const getAnalyticsEndpointsMock = () => [
	getGetDashboardMockHandler(),
	getGetAnalyticsOverviewMockHandler(),
	getGetPerformanceTrendMockHandler(),
	getGetTopPlayedMapsMockHandler(),
	getGetBestPerformingMapsMockHandler(),
	getGetDifficultyStatsMockHandler(),
	getGetMapTypeStatsMockHandler(),
	getGetScoreDistributionMockHandler(),
	getGetHourlyPlayStatsMockHandler(),
	getGetDailyPlayStatsMockHandler(),
	getGetAccuracyDistributionMockHandler(),
];
