/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.HonamiSystem.Server | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { BodyType, ErrorType } from "../../lib/custom-instance";

import { customInstance } from "../../lib/custom-instance";
import type {
	AddAgentParticipantRequest,
	AddUserParticipantRequest,
	ChatDetailResponse,
	ChatGroupResponse,
	ChatParticipantsResponse,
	ChatResponse,
	CreateChatGroupRequest,
	CreateChatRequest,
	SetChatGroupRequest,
	UpdateChatGroupRequest,
	UpdateChatRequest,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Create a new chat
 */
export const createChat = (
	createChatRequest: BodyType<CreateChatRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ChatResponse>(
		{
			url: `/api/chat`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createChatRequest,
			signal,
		},
		options,
	);
};

export const getCreateChatMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createChat>>,
		TError,
		{ data: BodyType<CreateChatRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createChat>>,
	TError,
	{ data: BodyType<CreateChatRequest> },
	TContext
> => {
	const mutationKey = ["createChat"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createChat>>,
		{ data: BodyType<CreateChatRequest> }
	> = (props) => {
		const { data } = props ?? {};

		return createChat(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateChatMutationResult = NonNullable<
	Awaited<ReturnType<typeof createChat>>
>;
export type CreateChatMutationBody = BodyType<CreateChatRequest>;
export type CreateChatMutationError = ErrorType<void>;

export const useCreateChat = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createChat>>,
			TError,
			{ data: BodyType<CreateChatRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createChat>>,
	TError,
	{ data: BodyType<CreateChatRequest> },
	TContext
> => {
	return useMutation(getCreateChatMutationOptions(options), queryClient);
};
/**
 * List the current user's chats
 */
export const listChats = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ChatResponse[]>(
		{ url: `/api/chat`, method: "GET", signal },
		options,
	);
};

export const getListChatsQueryKey = () => {
	return [`/api/chat`] as const;
};

export const getListChatsQueryOptions = <
	TData = Awaited<ReturnType<typeof listChats>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof listChats>>, TError, TData>
	>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListChatsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listChats>>> = ({
		signal,
	}) => listChats(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listChats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListChatsQueryResult = NonNullable<
	Awaited<ReturnType<typeof listChats>>
>;
export type ListChatsQueryError = ErrorType<void>;

export function useListChats<
	TData = Awaited<ReturnType<typeof listChats>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listChats>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listChats>>,
					TError,
					Awaited<ReturnType<typeof listChats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListChats<
	TData = Awaited<ReturnType<typeof listChats>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listChats>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listChats>>,
					TError,
					Awaited<ReturnType<typeof listChats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListChats<
	TData = Awaited<ReturnType<typeof listChats>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listChats>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListChats<
	TData = Awaited<ReturnType<typeof listChats>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listChats>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListChatsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get a chat by ID
 */
export const getChat = (
	chatId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ChatDetailResponse>(
		{ url: `/api/chat/${chatId}`, method: "GET", signal },
		options,
	);
};

export const getGetChatQueryKey = (chatId: string) => {
	return [`/api/chat/${chatId}`] as const;
};

export const getGetChatQueryOptions = <
	TData = Awaited<ReturnType<typeof getChat>>,
	TError = ErrorType<void>,
>(
	chatId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getChat>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetChatQueryKey(chatId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getChat>>> = ({
		signal,
	}) => getChat(chatId, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!chatId,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getChat>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetChatQueryResult = NonNullable<
	Awaited<ReturnType<typeof getChat>>
>;
export type GetChatQueryError = ErrorType<void>;

export function useGetChat<
	TData = Awaited<ReturnType<typeof getChat>>,
	TError = ErrorType<void>,
>(
	chatId: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getChat>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getChat>>,
					TError,
					Awaited<ReturnType<typeof getChat>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChat<
	TData = Awaited<ReturnType<typeof getChat>>,
	TError = ErrorType<void>,
>(
	chatId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getChat>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getChat>>,
					TError,
					Awaited<ReturnType<typeof getChat>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChat<
	TData = Awaited<ReturnType<typeof getChat>>,
	TError = ErrorType<void>,
>(
	chatId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getChat>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetChat<
	TData = Awaited<ReturnType<typeof getChat>>,
	TError = ErrorType<void>,
>(
	chatId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getChat>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetChatQueryOptions(chatId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Update chat metadata
 */
export const updateChat = (
	chatId: string,
	updateChatRequest: BodyType<UpdateChatRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ChatResponse>(
		{
			url: `/api/chat/${chatId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateChatRequest,
			signal,
		},
		options,
	);
};

export const getUpdateChatMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateChat>>,
		TError,
		{ chatId: string; data: BodyType<UpdateChatRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateChat>>,
	TError,
	{ chatId: string; data: BodyType<UpdateChatRequest> },
	TContext
> => {
	const mutationKey = ["updateChat"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateChat>>,
		{ chatId: string; data: BodyType<UpdateChatRequest> }
	> = (props) => {
		const { chatId, data } = props ?? {};

		return updateChat(chatId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateChatMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateChat>>
>;
export type UpdateChatMutationBody = BodyType<UpdateChatRequest>;
export type UpdateChatMutationError = ErrorType<void>;

export const useUpdateChat = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateChat>>,
			TError,
			{ chatId: string; data: BodyType<UpdateChatRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateChat>>,
	TError,
	{ chatId: string; data: BodyType<UpdateChatRequest> },
	TContext
> => {
	return useMutation(getUpdateChatMutationOptions(options), queryClient);
};
/**
 * Delete a chat
 */
export const deleteChat = (
	chatId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/chat/${chatId}`, method: "DELETE", signal },
		options,
	);
};

export const getDeleteChatMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteChat>>,
		TError,
		{ chatId: string },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteChat>>,
	TError,
	{ chatId: string },
	TContext
> => {
	const mutationKey = ["deleteChat"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteChat>>,
		{ chatId: string }
	> = (props) => {
		const { chatId } = props ?? {};

		return deleteChat(chatId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteChatMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteChat>>
>;

export type DeleteChatMutationError = ErrorType<void>;

export const useDeleteChat = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteChat>>,
			TError,
			{ chatId: string },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteChat>>,
	TError,
	{ chatId: string },
	TContext
> => {
	return useMutation(getDeleteChatMutationOptions(options), queryClient);
};
/**
 * Assign or unassign a chat to a group
 */
export const setChatGroup = (
	chatId: string,
	setChatGroupRequest: BodyType<SetChatGroupRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ChatResponse>(
		{
			url: `/api/chat/${chatId}/group`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: setChatGroupRequest,
			signal,
		},
		options,
	);
};

export const getSetChatGroupMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof setChatGroup>>,
		TError,
		{ chatId: string; data: BodyType<SetChatGroupRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof setChatGroup>>,
	TError,
	{ chatId: string; data: BodyType<SetChatGroupRequest> },
	TContext
> => {
	const mutationKey = ["setChatGroup"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof setChatGroup>>,
		{ chatId: string; data: BodyType<SetChatGroupRequest> }
	> = (props) => {
		const { chatId, data } = props ?? {};

		return setChatGroup(chatId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type SetChatGroupMutationResult = NonNullable<
	Awaited<ReturnType<typeof setChatGroup>>
>;
export type SetChatGroupMutationBody = BodyType<SetChatGroupRequest>;
export type SetChatGroupMutationError = ErrorType<void>;

export const useSetChatGroup = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof setChatGroup>>,
			TError,
			{ chatId: string; data: BodyType<SetChatGroupRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof setChatGroup>>,
	TError,
	{ chatId: string; data: BodyType<SetChatGroupRequest> },
	TContext
> => {
	return useMutation(getSetChatGroupMutationOptions(options), queryClient);
};
/**
 * List all participants in a chat
 */
export const getChatParticipants = (
	chatId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ChatParticipantsResponse>(
		{ url: `/api/chat/${chatId}/participants`, method: "GET", signal },
		options,
	);
};

export const getGetChatParticipantsQueryKey = (chatId: string) => {
	return [`/api/chat/${chatId}/participants`] as const;
};

export const getGetChatParticipantsQueryOptions = <
	TData = Awaited<ReturnType<typeof getChatParticipants>>,
	TError = ErrorType<void>,
>(
	chatId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChatParticipants>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetChatParticipantsQueryKey(chatId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getChatParticipants>>
	> = ({ signal }) => getChatParticipants(chatId, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!chatId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getChatParticipants>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChatParticipantsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getChatParticipants>>
>;
export type GetChatParticipantsQueryError = ErrorType<void>;

export function useGetChatParticipants<
	TData = Awaited<ReturnType<typeof getChatParticipants>>,
	TError = ErrorType<void>,
>(
	chatId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChatParticipants>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getChatParticipants>>,
					TError,
					Awaited<ReturnType<typeof getChatParticipants>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatParticipants<
	TData = Awaited<ReturnType<typeof getChatParticipants>>,
	TError = ErrorType<void>,
>(
	chatId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChatParticipants>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getChatParticipants>>,
					TError,
					Awaited<ReturnType<typeof getChatParticipants>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatParticipants<
	TData = Awaited<ReturnType<typeof getChatParticipants>>,
	TError = ErrorType<void>,
>(
	chatId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChatParticipants>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetChatParticipants<
	TData = Awaited<ReturnType<typeof getChatParticipants>>,
	TError = ErrorType<void>,
>(
	chatId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChatParticipants>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetChatParticipantsQueryOptions(chatId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Add a user as a participant to a chat
 */
export const addChatUserParticipant = (
	chatId: string,
	addUserParticipantRequest: BodyType<AddUserParticipantRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/chat/${chatId}/participants/user`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: addUserParticipantRequest,
			signal,
		},
		options,
	);
};

export const getAddChatUserParticipantMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof addChatUserParticipant>>,
		TError,
		{ chatId: string; data: BodyType<AddUserParticipantRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof addChatUserParticipant>>,
	TError,
	{ chatId: string; data: BodyType<AddUserParticipantRequest> },
	TContext
> => {
	const mutationKey = ["addChatUserParticipant"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof addChatUserParticipant>>,
		{ chatId: string; data: BodyType<AddUserParticipantRequest> }
	> = (props) => {
		const { chatId, data } = props ?? {};

		return addChatUserParticipant(chatId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AddChatUserParticipantMutationResult = NonNullable<
	Awaited<ReturnType<typeof addChatUserParticipant>>
>;
export type AddChatUserParticipantMutationBody =
	BodyType<AddUserParticipantRequest>;
export type AddChatUserParticipantMutationError = ErrorType<void>;

export const useAddChatUserParticipant = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof addChatUserParticipant>>,
			TError,
			{ chatId: string; data: BodyType<AddUserParticipantRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof addChatUserParticipant>>,
	TError,
	{ chatId: string; data: BodyType<AddUserParticipantRequest> },
	TContext
> => {
	return useMutation(
		getAddChatUserParticipantMutationOptions(options),
		queryClient,
	);
};
/**
 * Add an agent as a participant to a chat
 */
export const addChatAgentParticipant = (
	chatId: string,
	addAgentParticipantRequest: BodyType<AddAgentParticipantRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/chat/${chatId}/participants/agent`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: addAgentParticipantRequest,
			signal,
		},
		options,
	);
};

export const getAddChatAgentParticipantMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof addChatAgentParticipant>>,
		TError,
		{ chatId: string; data: BodyType<AddAgentParticipantRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof addChatAgentParticipant>>,
	TError,
	{ chatId: string; data: BodyType<AddAgentParticipantRequest> },
	TContext
> => {
	const mutationKey = ["addChatAgentParticipant"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof addChatAgentParticipant>>,
		{ chatId: string; data: BodyType<AddAgentParticipantRequest> }
	> = (props) => {
		const { chatId, data } = props ?? {};

		return addChatAgentParticipant(chatId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AddChatAgentParticipantMutationResult = NonNullable<
	Awaited<ReturnType<typeof addChatAgentParticipant>>
>;
export type AddChatAgentParticipantMutationBody =
	BodyType<AddAgentParticipantRequest>;
export type AddChatAgentParticipantMutationError = ErrorType<void>;

export const useAddChatAgentParticipant = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof addChatAgentParticipant>>,
			TError,
			{ chatId: string; data: BodyType<AddAgentParticipantRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof addChatAgentParticipant>>,
	TError,
	{ chatId: string; data: BodyType<AddAgentParticipantRequest> },
	TContext
> => {
	return useMutation(
		getAddChatAgentParticipantMutationOptions(options),
		queryClient,
	);
};
/**
 * Remove a user participant from a chat
 */
export const removeChatUserParticipant = (
	chatId: string,
	userId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/chat/${chatId}/participants/user/${userId}`,
			method: "DELETE",
			signal,
		},
		options,
	);
};

export const getRemoveChatUserParticipantMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof removeChatUserParticipant>>,
		TError,
		{ chatId: string; userId: string },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof removeChatUserParticipant>>,
	TError,
	{ chatId: string; userId: string },
	TContext
> => {
	const mutationKey = ["removeChatUserParticipant"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof removeChatUserParticipant>>,
		{ chatId: string; userId: string }
	> = (props) => {
		const { chatId, userId } = props ?? {};

		return removeChatUserParticipant(chatId, userId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RemoveChatUserParticipantMutationResult = NonNullable<
	Awaited<ReturnType<typeof removeChatUserParticipant>>
>;

export type RemoveChatUserParticipantMutationError = ErrorType<void>;

export const useRemoveChatUserParticipant = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof removeChatUserParticipant>>,
			TError,
			{ chatId: string; userId: string },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof removeChatUserParticipant>>,
	TError,
	{ chatId: string; userId: string },
	TContext
> => {
	return useMutation(
		getRemoveChatUserParticipantMutationOptions(options),
		queryClient,
	);
};
/**
 * Remove an agent participant from a chat
 */
export const removeChatAgentParticipant = (
	chatId: string,
	agentId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/chat/${chatId}/participants/agent/${agentId}`,
			method: "DELETE",
			signal,
		},
		options,
	);
};

export const getRemoveChatAgentParticipantMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof removeChatAgentParticipant>>,
		TError,
		{ chatId: string; agentId: string },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof removeChatAgentParticipant>>,
	TError,
	{ chatId: string; agentId: string },
	TContext
> => {
	const mutationKey = ["removeChatAgentParticipant"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof removeChatAgentParticipant>>,
		{ chatId: string; agentId: string }
	> = (props) => {
		const { chatId, agentId } = props ?? {};

		return removeChatAgentParticipant(chatId, agentId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RemoveChatAgentParticipantMutationResult = NonNullable<
	Awaited<ReturnType<typeof removeChatAgentParticipant>>
>;

export type RemoveChatAgentParticipantMutationError = ErrorType<void>;

export const useRemoveChatAgentParticipant = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof removeChatAgentParticipant>>,
			TError,
			{ chatId: string; agentId: string },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof removeChatAgentParticipant>>,
	TError,
	{ chatId: string; agentId: string },
	TContext
> => {
	return useMutation(
		getRemoveChatAgentParticipantMutationOptions(options),
		queryClient,
	);
};
/**
 * List the current user's chat groups
 */
export const listChatGroups = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ChatGroupResponse[]>(
		{ url: `/api/chat/groups`, method: "GET", signal },
		options,
	);
};

export const getListChatGroupsQueryKey = () => {
	return [`/api/chat/groups`] as const;
};

export const getListChatGroupsQueryOptions = <
	TData = Awaited<ReturnType<typeof listChatGroups>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof listChatGroups>>, TError, TData>
	>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListChatGroupsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listChatGroups>>> = ({
		signal,
	}) => listChatGroups(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listChatGroups>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListChatGroupsQueryResult = NonNullable<
	Awaited<ReturnType<typeof listChatGroups>>
>;
export type ListChatGroupsQueryError = ErrorType<void>;

export function useListChatGroups<
	TData = Awaited<ReturnType<typeof listChatGroups>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listChatGroups>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listChatGroups>>,
					TError,
					Awaited<ReturnType<typeof listChatGroups>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListChatGroups<
	TData = Awaited<ReturnType<typeof listChatGroups>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listChatGroups>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listChatGroups>>,
					TError,
					Awaited<ReturnType<typeof listChatGroups>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListChatGroups<
	TData = Awaited<ReturnType<typeof listChatGroups>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listChatGroups>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListChatGroups<
	TData = Awaited<ReturnType<typeof listChatGroups>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listChatGroups>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListChatGroupsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create a new chat group
 */
export const createChatGroup = (
	createChatGroupRequest: BodyType<CreateChatGroupRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ChatGroupResponse>(
		{
			url: `/api/chat/groups`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createChatGroupRequest,
			signal,
		},
		options,
	);
};

export const getCreateChatGroupMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createChatGroup>>,
		TError,
		{ data: BodyType<CreateChatGroupRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createChatGroup>>,
	TError,
	{ data: BodyType<CreateChatGroupRequest> },
	TContext
> => {
	const mutationKey = ["createChatGroup"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createChatGroup>>,
		{ data: BodyType<CreateChatGroupRequest> }
	> = (props) => {
		const { data } = props ?? {};

		return createChatGroup(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateChatGroupMutationResult = NonNullable<
	Awaited<ReturnType<typeof createChatGroup>>
>;
export type CreateChatGroupMutationBody = BodyType<CreateChatGroupRequest>;
export type CreateChatGroupMutationError = ErrorType<void>;

export const useCreateChatGroup = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createChatGroup>>,
			TError,
			{ data: BodyType<CreateChatGroupRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createChatGroup>>,
	TError,
	{ data: BodyType<CreateChatGroupRequest> },
	TContext
> => {
	return useMutation(getCreateChatGroupMutationOptions(options), queryClient);
};
/**
 * Update a chat group name
 */
export const updateChatGroup = (
	groupId: string,
	updateChatGroupRequest: BodyType<UpdateChatGroupRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<ChatGroupResponse>(
		{
			url: `/api/chat/groups/${groupId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateChatGroupRequest,
			signal,
		},
		options,
	);
};

export const getUpdateChatGroupMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateChatGroup>>,
		TError,
		{ groupId: string; data: BodyType<UpdateChatGroupRequest> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateChatGroup>>,
	TError,
	{ groupId: string; data: BodyType<UpdateChatGroupRequest> },
	TContext
> => {
	const mutationKey = ["updateChatGroup"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateChatGroup>>,
		{ groupId: string; data: BodyType<UpdateChatGroupRequest> }
	> = (props) => {
		const { groupId, data } = props ?? {};

		return updateChatGroup(groupId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateChatGroupMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateChatGroup>>
>;
export type UpdateChatGroupMutationBody = BodyType<UpdateChatGroupRequest>;
export type UpdateChatGroupMutationError = ErrorType<void>;

export const useUpdateChatGroup = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateChatGroup>>,
			TError,
			{ groupId: string; data: BodyType<UpdateChatGroupRequest> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateChatGroup>>,
	TError,
	{ groupId: string; data: BodyType<UpdateChatGroupRequest> },
	TContext
> => {
	return useMutation(getUpdateChatGroupMutationOptions(options), queryClient);
};
/**
 * Delete a chat group
 */
export const deleteChatGroup = (
	groupId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/chat/groups/${groupId}`, method: "DELETE", signal },
		options,
	);
};

export const getDeleteChatGroupMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteChatGroup>>,
		TError,
		{ groupId: string },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteChatGroup>>,
	TError,
	{ groupId: string },
	TContext
> => {
	const mutationKey = ["deleteChatGroup"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteChatGroup>>,
		{ groupId: string }
	> = (props) => {
		const { groupId } = props ?? {};

		return deleteChatGroup(groupId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteChatGroupMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteChatGroup>>
>;

export type DeleteChatGroupMutationError = ErrorType<void>;

export const useDeleteChatGroup = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteChatGroup>>,
			TError,
			{ groupId: string },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteChatGroup>>,
	TError,
	{ groupId: string },
	TContext
> => {
	return useMutation(getDeleteChatGroupMutationOptions(options), queryClient);
};
