/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AnalyticsOverviewDto } from "./analyticsOverviewDto";
import type { DailyPlayStatsDto } from "./dailyPlayStatsDto";
import type { MapPlayStatsDto } from "./mapPlayStatsDto";
import type { PerformanceTrendDto } from "./performanceTrendDto";
import type { PlaySessionSummaryDto } from "./playSessionSummaryDto";
import type { ScoreDistributionDto } from "./scoreDistributionDto";

export interface DashboardDto {
	overview?: AnalyticsOverviewDto;
	recentSessions?: PlaySessionSummaryDto[];
	topPlayedMaps?: MapPlayStatsDto[];
	recentTrend?: PerformanceTrendDto[];
	scoreDistribution?: ScoreDistributionDto[];
	dailyStats?: DailyPlayStatsDto[];
}
