/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface DifficultyDto {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	id?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	mapId?: number | string;
	mapType?: string;
	difficulty?: string;
	/** @nullable */
	customDifficultyLabel?: string | null;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	njs?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	pp?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	star?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	playCount?: number | string;
}
