/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetPlaySessionsParams = {
	/**
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	mapId?: number | string;
	mapHash?: string;
	endReason?: string;
	fromDate?: string;
	toDate?: string;
	practiceMode?: boolean;
	multiplayer?: boolean;
	difficulty?: string;
	mapType?: string;
	fullCombo?: boolean;
	/**
	 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
	 */
	minAccuracy?: number | string;
	/**
	 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
	 */
	maxAccuracy?: number | string;
	/**
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	page?: number | string;
	/**
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	pageSize?: number | string;
	sortBy?: string;
	sortDescending?: boolean;
};
