/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface HourlyPlayStatsDto {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	hour?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	playCount?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	averageAccuracy?: number | string;
}
