/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DifficultyDto } from "./difficultyDto";

export interface MapDto {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	id?: number | string;
	hash?: string;
	songName?: string;
	songSubName?: string;
	songAuthor?: string;
	mapper?: string;
	/** @nullable */
	bsrKey?: string | null;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	duration?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	bpm?: number | string;
	hasCoverImage?: boolean;
	gameVersion?: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	playCount?: number | string;
	difficulties?: DifficultyDto[];
}
