/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MapPlayStatsDto {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	mapId?: number | string;
	songName?: string;
	songAuthor?: string;
	mapper?: string;
	hasCoverImage?: boolean;
	/** @nullable */
	bsrKey?: string | null;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	playCount?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	averageAccuracy?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	averageScorePercentage?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	fullComboCount?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	bestScore?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	bestScorePercentage?: number | string;
	/** @nullable */
	bestRank?: string | null;
	lastPlayedAt?: string;
}
