/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LiveDataSnapshotDto } from "./liveDataSnapshotDto";

export interface PaginatedResultOfLiveDataSnapshotDto {
	items?: LiveDataSnapshotDto[];
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalCount?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	page?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	pageSize?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalPages?: number | string;
	hasPrevious?: boolean;
	hasNext?: boolean;
}
