/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PlaySessionSummaryDto {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	id?: number | string;
	startedAt?: string;
	/** @nullable */
	finishedAt?: string | null;
	/** @nullable */
	endReason?: string | null;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	durationSeconds?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	mapId?: number | string;
	songName?: string;
	songAuthor?: string;
	mapper?: string;
	hasCoverImage?: boolean;
	difficulty?: string;
	mapType?: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	finalScore?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	finalMaxScore?: number | string;
	/** @nullable */
	finalRank?: string | null;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	finalAccuracy?: number | string;
	finalFullCombo?: boolean;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	finalMisses?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	scorePercentage?: number | string;
}
