/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

import type { RequestHandlerOptions } from "msw";
import { HttpResponse, http } from "msw";

export const getGetMapsMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/maps",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetMapByIdMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/maps/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetMapDetailMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/maps/:id/detail",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetMapDifficultiesMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/maps/:id/difficulties",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetMapSessionsMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/maps/:id/sessions",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetMapCoverMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/maps/:id/cover",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetMapByHashMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/maps/hash/:hash",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetMapCoverByHashMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/maps/hash/:hash/cover",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetMapByBSRKeyMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/maps/bsr/:bsrKey",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetMapCoverByBSRKeyMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/maps/bsr/:bsrKey/cover",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};
export const getMapEndpointsMock = () => [
	getGetMapsMockHandler(),
	getGetMapByIdMockHandler(),
	getGetMapDetailMockHandler(),
	getGetMapDifficultiesMockHandler(),
	getGetMapSessionsMockHandler(),
	getGetMapCoverMockHandler(),
	getGetMapByHashMockHandler(),
	getGetMapCoverByHashMockHandler(),
	getGetMapByBSRKeyMockHandler(),
	getGetMapCoverByBSRKeyMockHandler(),
];
