/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.HonamiSystem.Server | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { BodyType, ErrorType } from "../../lib/custom-instance";

import { customInstance } from "../../lib/custom-instance";
import type {
	ChangePasswordDto,
	HttpValidationProblemDetails,
	LoginDto,
	RegisterDto,
	UserInfoDto,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Register a new user account
 */
export const register = (
	registerDto: BodyType<RegisterDto>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/account/register`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: registerDto,
			signal,
		},
		options,
	);
};

export const getRegisterMutationOptions = <
	TError = ErrorType<HttpValidationProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof register>>,
		TError,
		{ data: BodyType<RegisterDto> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof register>>,
	TError,
	{ data: BodyType<RegisterDto> },
	TContext
> => {
	const mutationKey = ["register"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof register>>,
		{ data: BodyType<RegisterDto> }
	> = (props) => {
		const { data } = props ?? {};

		return register(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
	Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = BodyType<RegisterDto>;
export type RegisterMutationError = ErrorType<HttpValidationProblemDetails>;

export const useRegister = <
	TError = ErrorType<HttpValidationProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof register>>,
			TError,
			{ data: BodyType<RegisterDto> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof register>>,
	TError,
	{ data: BodyType<RegisterDto> },
	TContext
> => {
	return useMutation(getRegisterMutationOptions(options), queryClient);
};
/**
 * Log in with credentials
 */
export const login = (
	loginDto: BodyType<LoginDto>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/account/login`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: loginDto,
			signal,
		},
		options,
	);
};

export const getLoginMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof login>>,
		TError,
		{ data: BodyType<LoginDto> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof login>>,
	TError,
	{ data: BodyType<LoginDto> },
	TContext
> => {
	const mutationKey = ["login"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof login>>,
		{ data: BodyType<LoginDto> }
	> = (props) => {
		const { data } = props ?? {};

		return login(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = BodyType<LoginDto>;
export type LoginMutationError = ErrorType<void>;

export const useLogin = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof login>>,
			TError,
			{ data: BodyType<LoginDto> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof login>>,
	TError,
	{ data: BodyType<LoginDto> },
	TContext
> => {
	return useMutation(getLoginMutationOptions(options), queryClient);
};
/**
 * Log out the current session
 */
export const logout = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/account/logout`, method: "POST", signal },
		options,
	);
};

export const getLogoutMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof logout>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof logout>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["logout"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof logout>>,
		void
	> = () => {
		return logout(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
	Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = ErrorType<unknown>;

export const useLogout = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof logout>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof logout>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getLogoutMutationOptions(options), queryClient);
};
/**
 * Get the current authenticated user info
 */
export const getMe = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UserInfoDto>(
		{ url: `/api/account/me`, method: "GET", signal },
		options,
	);
};

export const getGetMeQueryKey = () => {
	return [`/api/account/me`] as const;
};

export const getGetMeQueryOptions = <
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
	>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
		signal,
	}) => getMe(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getMe>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorType<void>;

export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMe>>,
					TError,
					Awaited<ReturnType<typeof getMe>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMe>>,
					TError,
					Awaited<ReturnType<typeof getMe>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMeQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Change the current user's password
 */
export const changePassword = (
	changePasswordDto: BodyType<ChangePasswordDto>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/account/change-password`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: changePasswordDto,
			signal,
		},
		options,
	);
};

export const getChangePasswordMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof changePassword>>,
		TError,
		{ data: BodyType<ChangePasswordDto> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof changePassword>>,
	TError,
	{ data: BodyType<ChangePasswordDto> },
	TContext
> => {
	const mutationKey = ["changePassword"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof changePassword>>,
		{ data: BodyType<ChangePasswordDto> }
	> = (props) => {
		const { data } = props ?? {};

		return changePassword(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ChangePasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof changePassword>>
>;
export type ChangePasswordMutationBody = BodyType<ChangePasswordDto>;
export type ChangePasswordMutationError = ErrorType<void>;

export const useChangePassword = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof changePassword>>,
			TError,
			{ data: BodyType<ChangePasswordDto> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof changePassword>>,
	TError,
	{ data: BodyType<ChangePasswordDto> },
	TContext
> => {
	return useMutation(getChangePasswordMutationOptions(options), queryClient);
};
