/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Shiron.ResonanceSystem.API | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

import type {
	OCRResultDTO,
	PostApiScanWuwaBotBody,
	PostApiScanWuwaBotParams,
} from "../model";

export type postApiScanWuwaBotResponse200 = {
	data: OCRResultDTO;
	status: 200;
};

export type postApiScanWuwaBotResponseSuccess =
	postApiScanWuwaBotResponse200 & {
		headers: Headers;
	};

export type postApiScanWuwaBotResponse = postApiScanWuwaBotResponseSuccess;

export const getPostApiScanWuwaBotUrl = (params?: PostApiScanWuwaBotParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/scan/wuwa-bot?${stringifiedParams}`
		: `/api/scan/wuwa-bot`;
};

export const postApiScanWuwaBot = async (
	postApiScanWuwaBotBody: PostApiScanWuwaBotBody,
	params?: PostApiScanWuwaBotParams,
	options?: RequestInit,
): Promise<postApiScanWuwaBotResponse> => {
	const formData = new FormData();
	formData.append(`file`, postApiScanWuwaBotBody.file);

	const res = await fetch(getPostApiScanWuwaBotUrl(params), {
		...options,
		method: "POST",
		body: formData,
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: postApiScanWuwaBotResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as postApiScanWuwaBotResponse;
};

export const getPostApiScanWuwaBotMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiScanWuwaBot>>,
		TError,
		{ data: PostApiScanWuwaBotBody; params?: PostApiScanWuwaBotParams },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiScanWuwaBot>>,
	TError,
	{ data: PostApiScanWuwaBotBody; params?: PostApiScanWuwaBotParams },
	TContext
> => {
	const mutationKey = ["postApiScanWuwaBot"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiScanWuwaBot>>,
		{ data: PostApiScanWuwaBotBody; params?: PostApiScanWuwaBotParams }
	> = (props) => {
		const { data, params } = props ?? {};

		return postApiScanWuwaBot(data, params, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiScanWuwaBotMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiScanWuwaBot>>
>;
export type PostApiScanWuwaBotMutationBody = PostApiScanWuwaBotBody;
export type PostApiScanWuwaBotMutationError = unknown;

export const usePostApiScanWuwaBot = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiScanWuwaBot>>,
			TError,
			{ data: PostApiScanWuwaBotBody; params?: PostApiScanWuwaBotParams },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiScanWuwaBot>>,
	TError,
	{ data: PostApiScanWuwaBotBody; params?: PostApiScanWuwaBotParams },
	TContext
> => {
	return useMutation(
		getPostApiScanWuwaBotMutationOptions(options),
		queryClient,
	);
};
